### PR TITLE
cli: tap: Use safe accessors

### LINKED ISSUE #47: Tap panic after a while
Unfortunately, I don't yet have a consistent repro, but I've hit this panic twice with `conduit tap` while sending lots of gRPC requests to a conduit-injected deployment:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1d0bb22]

goroutine 1 [running]:
github.com/runconduit/conduit/cli/cmd.print(0x285b500, 0xc42000a240)
	/go/src/github.com/runconduit/conduit/cli/cmd/tap.go:135 +0x9d2
github.com/runconduit/conduit/cli/cmd.glob..func6(0x28a4b40, 0xc4202ca980, 0x2, 0x2, 0x0, 0x0)
	/go/src/github.com/runconduit/conduit/cli/cmd/tap.go:77 +0x2d5
github.com/runconduit/conduit/vendor/github.com/spf13/cobra.(*Command).execute(0x28a4b40, 0xc4202ca8e0, 0x2, 0x2, 0x28a4b40, 0xc4202ca8e0)
	/go/src/github.com/runconduit/conduit/vendor/github.com/spf13/cobra/command.go:698 +0x47a
github.com/runconduit/conduit/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x28a4700, 0x20725e0, 0xc42056ff70, 0x10043a4)
	/go/src/github.com/runconduit/conduit/vendor/github.com/spf13/cobra/command.go:783 +0x30e
github.com/runconduit/conduit/vendor/github.com/spf13/cobra.(*Command).Execute(0x28a4700, 0x1d57ddc, 0xc4202ca860)
	/go/src/github.com/runconduit/conduit/vendor/github.com/spf13/cobra/command.go:736 +0x2b
main.main()
	/go/src/github.com/runconduit/conduit/cli/main.go:14 +0x31
```

I am using a custom-built Conduit version, which consists of master commit 81fb0fe onto which I have merged 22475d4 (from `alex/rbac` branch) and c31e892 (from `alex/skip-outbound-ports` branch).

I'm using the `conduit` CLI bin from the built image, and my `conduit install` and `conduit injects` are referencing my custom-built images.

### PR DESCRIPTION
**Pull request by olix0r**
The `tap` command is prone to segmentation faults due to use of `nil`
values. This is because we don't use the safe `Get*()` field accessors.

This change fixes several unsafe field access paths.

Fixes #47

### CODE REVIEW

File: cli/cmd/tap.go [hunk 1]
```diff
@@ -259,19 +259,19 @@ func renderTapEvent(event *common.TapEvent) string {
...
 	)
 
-	http := event.GetHttp()
-	httpEvent := http.Event
+	httpEvent := event.GetHttp().GetEvent()
 	switch ev := httpEvent.(type) {
 	case *common.TapEvent_Http_RequestInit_:
 		return fmt.Sprintf("req id=%d:%d %s :method=%s :authority=%s :path=%s secured=%s",
 			ev.RequestInit.Id.Base,
 			ev.RequestInit.Id.Stream,
```
Comment (klingerf) [inline cli/cmd/tap.go]: Maybe we should switch these as well?

```
			ev.RequestInit.GetId().GetBase(),
			ev.RequestInit.GetId().GetStream(),
```

Or is it safe to assume that `Id` is always present? If you do decide to update it, can you update it in each of the following cases as well?

File: cli/cmd/tap.go [hunk 2]
```diff
@@ -281,10 +281,10 @@ func renderTapEvent(event *common.TapEvent) string {
 			ev.ResponseInit.GetSinceRequestInit().Nanos/1000,
```
Comment (klingerf) [inline cli/cmd/tap.go]: I rolled back to the commit where the initial tap panic was reported in #47, and it looks like it's a result of this `.Nanos` call. It should be:

```
			ev.ResponseInit.GetSinceRequestInit().GetNanos()/1000,
```

I think you should also update all of the `.Nanos` calls as part of this branch.

**Comment by olix0r** [comment]
@klingerf Good catches! I think I've addressed these. Let me know how this most recent diff looks.

File: cli/cmd/tap.go (hunk 2 above)
Comment (klingerf) [reply cli/cmd/tap.go]: Looks like you missed this `.Nanos` call. Otherwise LGTM.

Comment (olix0r) [reply cli/cmd/tap.go]: heh, sed gone wrong
