### PR TITLE
proxy: Fix Inotify falling back to polling when files don't exist yet

### LINKED ISSUE #1061: proxy: Test filesystem watching code with a Kubernetes ConfigMap
We should ensure the filesystem watching code added in 7220fb53670e2bfe2d9424d97edcd40d4d839a83 is able to detect changes in a Kubernetes ConfigMap as a volume mount. @klingerf informs me that in the past, we ran into some issues where changes to ConfigMaps don't correctly change the last modified timestamp. This may have been fixed in Kubernetes, so we should do some testing to determine if this works.

### LINKED ISSUE #1090: proxy: Fs polling code doesn't detect changes within the same second (on macOS)
I've been working on writing tests for the filesystem watching code added in #1056 and #1077, and have found a bug:

When multiple watched files are created or modified within 1 second of each other, the polling-based watch stream only detects one change, at least on macOS. This is because the last modified timestamps in the filesystem metadata are reported with 1-second resolution on macOS.

According to the 2008 POSIX standard, the `stat.st_mtim` field is _supposed_ to be reported as a `timespec` with nanosecond resolution, but it appears that macOS does not set the nanoseconds field. I suspect other Unices implement this correctly.

### LINKED ISSUE #1097: Inotify init will fail if watched certs don't exist yet
As  seen in [this CI build](https://travis-ci.org/runconduit/conduit/jobs/389959060). The `Inotify::init` function will fail if the watched path doesn't exist yet. Currently, the proxy will fall back to polling the fs in this case, so we don't _break_ here, however, we'll continue polling indefinitely, which is not ideal. 

When we're on Linux, if creating the `Inotify` watch fails with `io::ErrorKind::NotFound`, we should poll until the file exists and then try `inotify` again. We should still fall back to polling on other errors.

### PR DESCRIPTION
**Pull request by hawkw**
This PR changes the proxy's Inotify watch code to avoid always falling back to
polling the filesystem when the watched files don't exist yet. It also contains
some additional cleanup and refactoring of the inotify code, including moving
the non-TLS-specific filesystem watching code out of the `tls::config` module
and into a new `fs_watch` module.

In addition, it adds tests for both the polling-based and inotify-based watch
implementations, and changes the polling-based watches to hash the files rather
than using timestamps from the file's metadata to detect changes. These changes
are originally from #1094 and #1091, respectively, but they're included here
because @briansmith asked that all the changes be made in one PR.

Closes #1094. Closes #1091. Fixes #1090. Fixes #1097. Fixes #1061.

Signed-off-by: Eliza Weisman <eliza@buoyant.io>

### CODE REVIEW

File: proxy/src/transport/tls/config.rs [hunk 1]
```diff
@@ -367,3 +342,886 @@ fn set_common_settings(versions: &mut Vec<rustls::ProtocolVersion>) {
...
+        stream: impl Stream<Item = (), Error=()> + 'static,
+    ) {
+        let Fixture { cfg, dir: _dir, mut rt } = fixture;
+
+        let (watch, bg) = watch_stream(stream);
+        rt.spawn(bg);
+
+        let f = File::create(cfg.trust_anchors)
+            .expect("create trust anchors");
+        f.sync_all().expect("create trust anchors");
```
Comment (briansmith) [inline proxy/src/transport/tls/config.rs]: Why do we need to call sync_all(), especially so many times?

File: proxy/src/transport/tls/config.rs [hunk 2]
```diff
@@ -367,3 +342,886 @@ fn set_common_settings(versions: &mut Vec<rustls::ProtocolVersion>) {
...
+    trait BlockOnFor {
+        /// Runs the provided future for up to `Duration`, blocking the thread
+        /// until the future completes.
+        fn block_on_for<F>(&mut self, duration: Duration, f: F) -> Result<F::Item, F::Error>
+        where
+            F: Future;
+    }
+
+    impl BlockOnFor for Runtime {
+        fn block_on_for<F>(&mut self, duration: Duration, f: F) -> Result<F::Item, F::Error>
```
Comment (briansmith) [inline proxy/src/transport/tls/config.rs]: I think `duration` is maybe better named `timeout`?

Why do we need a timeout at all? If we removed the timeout, would any/all of the tests wait forever?

File: proxy/src/transport/tls/config.rs [hunk 3]
```diff
@@ -367,3 +342,886 @@ fn set_common_settings(versions: &mut Vec<rustls::ProtocolVersion>) {
...
+        assert!(item.is_some());
+
+        let f = File::create(cfg.private_key)
+            .expect("create private key");
+        f.sync_all()
+            .expect("sync private key");
+        println!("created {:?}", f);
+
+        let next = watch.into_future().map_err(|(e, _)| e);
+        let (item, _) = rt.block_on_for(Duration::from_secs(2), next)
```
Comment (briansmith) [inline proxy/src/transport/tls/config.rs]: Why are some of the timeouts 2 seconds and others 5 seconds?

File: proxy/src/transport/tls/config.rs [hunk 4]
```diff
@@ -367,3 +342,886 @@ fn set_common_settings(versions: &mut Vec<rustls::ProtocolVersion>) {
...
+            .expect("symlink private key");
+
+        let next = watch.into_future().map_err(|(e, _)| e);
+        let (item, watch) = rt.block_on_for(Duration::from_secs(5), next)
+            .expect("second change");
+        assert!(item.is_some());
+
+        // Sleep briefly between changing the fs, as a workaround for
+        // macOS reporting timestamps with second resolution.
+        // https://github.com/runconduit/conduit/issues/1090
```
Comment (briansmith) [inline proxy/src/transport/tls/config.rs]: Since we're not using timestamps any more, can we clean this up?

File: proxy/src/transport/tls/config.rs [hunk 5]
```diff
@@ -367,3 +342,886 @@ fn set_common_settings(versions: &mut Vec<rustls::ProtocolVersion>) {
...
+        fs::create_dir(&real_data_path).expect("create data dir");
+        fs::create_dir(&real_data_path_2).expect("create data dir 2");
+        symlink_dir(&real_data_path, &data_path).expect("create data dir symlink");
+
+        let mut trust_anchors = File::create(real_data_path.clone().join(TRUST_ANCHORS))
+            .expect("create trust anchors");
+        println!("created {:?}", trust_anchors);
+        trust_anchors.write_all(b"I am not real trust anchors")
+            .expect("write to trust anchors");
+        trust_anchors.sync_all().expect("sync trust anchors");
```
Comment (briansmith) [inline proxy/src/transport/tls/config.rs]: Is it really valuable to have the `expect()` messages everywhere? Why not just `unwrap()` and make the code easier to read? If we need to know what failed we can use the backtrace.

It seems like this `File::create...write_all...sync_all()` pattern should be encapsulated into a function that's reused.

Similarly, we should encapsulate the larger logic of "create a file in one directory and then create a symlink to it in another directory" and the larger logic "create the file and the first symlink and then create the second symlink."

More generally, I can't really carefully review this much repetitive testing code. I tried last night and again today and it's just overwhelming. So, the less code there actually is in the test, and the more reusable functions are reused, the better.

File: proxy/src/transport/tls/config.rs [hunk 6]
```diff
@@ -367,3 +342,886 @@ fn set_common_settings(versions: &mut Vec<rustls::ProtocolVersion>) {
...
+        io::{self, Write},
+        fs::{self, File},
+        thread,
+    };
+
+    use futures::{Sink, Stream};
+    use futures_watch::Watch;
+
+    // These functions are a workaround for Windows having separate API calls
+    // for symlinking files and directories. You're welcome, Brian ;)
```
[the remark this answers is not in the document]
Comment (hawkw) [reply proxy/src/transport/tls/config.rs]: > Usually Windows won't let a non-privileged process create symlinks.

Ah, I wasn't aware of that. In that case, I'll just disable these tests on Windows.

File: proxy/src/transport/tls/config.rs (hunk 5 above)
Comment (hawkw) [reply proxy/src/transport/tls/config.rs]: > It seems like this `File::create...write_all...sync_all()` pattern should be encapsulated into a function that's reused.

I agree. I  intended to do this in a separate follow-up PR, as I wanted to get this up for review sooner, but I'd be happy to make that change now if you prefer.

File: proxy/src/transport/tls/config.rs (hunk 2 above)
Comment (hawkw) [reply proxy/src/transport/tls/config.rs]: > Why do we need a timeout at all? If we removed the timeout, would any/all of the tests wait forever?

Not when the functionality we're testing for works correctly; however, before everything was working correctly, the failure mode was waiting forever. I found that this made debugging failing tests more difficult, as killing the tests when one has been waiting for over a minute prevents any remaining tests from running, and doesn't print any output from the killed test.

Comment (briansmith) [reply proxy/src/transport/tls/config.rs]: OK, I think it's fine to leave the timeouts in. We can remove them later if we find they get in the way. It would be good to add a comment to the constructor function that explains basically what you just said here.

**Comment by hawkw** [comment]
> I'm hoping if we move the file watching code to its own module, and create some utilities functions that serve as building-blocks for the tests and put them in that module, then the tests themselves will get smaller.

I completely agree that a lot of the repeated testing code needs to be factored out.

Initially, I wasn't sure if the watching code should go in its own module, as it seemed like making this code less TLS-config-specific might introduce some additional complexity, but I can do that if you'd prefer.

File: proxy/src/transport/tls/config.rs (hunk 2 above)
Comment (hawkw) [reply proxy/src/transport/tls/config.rs]: Okay, I'll add a comment here.

I was considering moving this to another module, as I think we currently have a number of tests whose failure modes are waiting forever rather than panicking, and changing them to use this might make debugging any regressions that break those tests a bit easier.

**Comment by briansmith** [comment]
> Initially, I wasn't sure if the watching code should go in its own module, as it seemed like making this code less TLS-config-specific might introduce some additional complexity, but I can do that if you'd prefer.

I think if it's a significant amount of effort to move the generic logic to its own module, then we shouldn't do it. However, during the review I noticed that once we map things to a list of `PathBuf`s then it seems like it's all totally generic anyway.

The test fixture is definitely specific to our TLS stuff. In an ideal world we'd refactor the tests so that we have generic file watching tests in the new module, and then TLS-specific tests in the tls/config.rs module. However, that's not reasonable to do now, so we can just leave the tests in the tls/config.rs module for now (probably forever) without trying to make them generic. The utilities like "create a file with two symlinks" can/should go in the generic module, though, I think.

**Comment by briansmith** [comment]
(Moving it to a module outside of `transport/tls` does mean that the `ring` and `untrusted` `extern crate` declarations need to be moved to lib.rs. That's OK with me.)

**Comment by hawkw** [comment]
@briansmith, I think as of d6d17a85580a4b82ad1f34217829cb253287ecf2, I've now made all the changes you've requested?

File: proxy/src/transport/tls/config.rs [hunk 7]
```diff
@@ -367,3 +235,573 @@ fn set_common_settings(versions: &mut Vec<rustls::ProtocolVersion>) {
...
+
+    impl Fixture {
+        fn new() -> Fixture {
+            let _ = ::env_logger::try_init();
+            let dir = TempDir::new("certs").unwrap();
+            let cfg = CommonSettings {
+                trust_anchors: dir.path().join(TRUST_ANCHORS),
+                end_entity_cert: dir.path().join(END_ENTITY_CERT),
+                private_key: dir.path().join(PRIVATE_KEY),
+            };
```
Comment (briansmith) [inline proxy/src/transport/tls/config.rs]: OK, now I can read the tests much better. I see that there's actually nothing TLS-specific about these tests except that they use `CommonSettings` to determine which files to look at, right?

Imagine that you replaced `cfg` with `paths: Vec<PathBuf>` or similar. Then all these tests would be completely independent of the `tls` submodule and they could all easily be moved to the fs_watch submodule. Not only that, but even more repetitive code in the tests could be replaced because you could just loop over the contents of `paths` (even now, they could be replaced with `for x in &[&fixture.cfg.trust_anchors, ...]` or similar).

Besides these tests that verify that the FS watching code works, in `tls/config.rs` (or, hopefully, somewhere under `tests/`) we're going to need to add tests that verify (1) When the input are initially not valid certificates/ca-bundles/private-keys, we ignore them, (2) When the inputs become valid, we construct a valid configuration from them, and (3) When we have a valid configuration and the files change to an invalid configuration, we ignore the change.

Comment (briansmith) [reply proxy/src/transport/tls/config.rs]: > Besides these tests that verify that the FS watching code works, in tls/config.rs (or, hopefully, somewhere under tests/) we're going to need to add tests that verify (1) When the input are initially not valid certificates/ca-bundles/private-keys, we ignore them, (2) When the inputs become valid, we construct a valid configuration from them, and (3) When we have a valid configuration and the files change to an invalid configuration, we ignore the change.

^ Not in this PR, though.

File: proxy/src/transport/tls/config.rs [hunk 8]
```diff
@@ -367,3 +235,571 @@ fn set_common_settings(versions: &mut Vec<rustls::ProtocolVersion>) {
...
+                .unwrap()
+                .map_err(|e| panic!("{}", e));
+            let (watch, bg) = watch_stream(stream);
+            test(self, watch, bg)
+        }
+    }
+
+    fn create_file<P: AsRef<Path>>(path: P) -> io::Result<File> {
+        let f = File::create(path)?;
+        f.sync_all()?;
```
[the remark this answers is not in the document]
Comment (hawkw) [reply proxy/src/transport/tls/config.rs]: I don't think it's strictly necessary here, but I thought flushing every filesystem operation immediately might help prevent the tests from being flaky.

File: proxy/src/transport/tls/config.rs (hunk 7 above)
Comment (hawkw) [reply proxy/src/transport/tls/config.rs]: This is a fair point. I'll make the tests more generic and move them to the `fs_watch` module.

**Comment by hawkw** [comment]
@briansmith as of https://github.com/runconduit/conduit/pull/1119/commits/acdc91ef4a9c2c72656149deb6749692f9303581, the tests are now no longer TLS-specific, and have been moved to the `fs_watch` module. 

I'll start looking into adding integration tests for the TLS specific functionality in an additional branch, as well.

**Comment by hawkw** [comment]
I think the Travis build of acdc91e errored for unrelated reasons:
screen shot 2018-06-14 at 4 26 45 pm

I'll go ahead and restart it.

File: proxy/src/fs_watch.rs [hunk 9]
```diff
@@ -0,0 +1,701 @@
...
+                .join(path.file_name().unwrap());
+            create_and_write(path, b"b").unwrap();
+        }
+
+        rt.spawn(bg);
+
+        fs::remove_dir_all(&data_path).unwrap();
+        symlink(&real_data_path_2, &data_path).unwrap();
+
+        let (item, _) = next_change(&mut rt, watch).unwrap();
```
Comment (briansmith) [inline proxy/src/fs_watch.rs]: Did you verify that if you comment out the two lines above this, then `next_change() ` will hang because there's no notifications? That is, did you verify that the `symlink()` call above is actually what causes the notification?

File: proxy/src/fs_watch.rs [hunk 10]
```diff
@@ -0,0 +1,701 @@
...
+
+
+        fn add_paths(&mut self) -> Result<(), io::Error> {
+            let mask
+                = WatchMask::CREATE
+                | WatchMask::MODIFY
+                | WatchMask::DELETE
+                | WatchMask::DELETE_SELF
+                | WatchMask::MOVE
+                | WatchMask::MOVE_SELF
```
Comment (briansmith) [inline proxy/src/fs_watch.rs]: Shouldn't we include `IN_ONLYDIR` too? Otherwise, this looks right to me, though it's not clear to me whether or not we want to use `IN_EXCL_UNLINK`. Something to figure out later.

File: proxy/src/fs_watch.rs [hunk 11]
```diff
@@ -0,0 +1,701 @@
...
+    }
+
+}
+
+/// Stream changes by polling the filesystem.
+///
+/// This will calculate the SHA-384 hash of each of files at the paths
+/// described by this `CommonSettings` every `interval`, and attempt to
+/// load a new `CommonConfig` from the files again if any of the hashes
+/// has changed.
```
[the remark this answers is not in the document]
Comment (hawkw) [reply proxy/src/fs_watch.rs]: Yeah, I thought about that as well. It seemed out of scope for _this_ branch, though, especially given that I think false negatives are much more likely to be a problem than false positives.

File: proxy/src/fs_watch.rs (hunk 10 above)
Comment (hawkw) [reply proxy/src/fs_watch.rs]: > Shouldn't we include `IN_ONLYDIR` too? 

When a file exists when starting the watch, we _do_ watch the actual file, so I didn't add that mask flag

Comment (briansmith) [reply proxy/src/fs_watch.rs]: > When a file exists when starting the watch, we do watch the actual file, so I didn't add that mask flag

Ah, yeah. Why do we do that? It seems like it would always be correct to watch the parent directory regardless of whether the file initially exists. Generally unnecessary special cases are bad and "file existed at the beginning" seems like a special case.

File: proxy/src/fs_watch.rs (hunk 9 above)
Comment (hawkw) [reply proxy/src/fs_watch.rs]: Ah, you're right, this test still passes with those lines removed. Thanks for catching that!

 I've added a call to `next_change(...)` prior to creating the symlink, after which the test _will_ fail if we don't create the symlink.

File: proxy/src/fs_watch.rs [hunk 12]
```diff
@@ -0,0 +1,703 @@
...
+            create_and_write(path, b"A").unwrap();
+
+            let (item, watch) = next_change(&mut rt, watch).unwrap();
+            assert!(item.is_some());
+            watch
+        });
+
+        for path in &paths {
+            fs::remove_file(path).unwrap();
+            println!("deleted {:?}", path);
```
Comment (briansmith) [inline proxy/src/fs_watch.rs]: It seems like here we need `assert!(item.is_some());` too. And maybe other places?

File: proxy/src/fs_watch.rs [hunk 13]
```diff
@@ -0,0 +1,703 @@
...
+            .map_err(|_| ());
+
+        (watch, Box::new(f))
+    }
+
+    fn next_change(rt: &mut Runtime, watch: Watch<()>)
+        -> Result<(Option<()>, Watch<()>), WatchError>
+    {
+        let next = watch.into_future().map_err(|(e, _)| e);
+        rt.block_on_for(Duration::from_secs(2), next)
```
Comment (briansmith) [inline proxy/src/fs_watch.rs]: Another thing I just noticed: Now that everything is working as intended, should we really have this timeout? It seems like it will result in a flaky test?

File: proxy/src/fs_watch.rs (hunk 10 above)
Comment (hawkw) [reply proxy/src/fs_watch.rs]: We always watch the files we care about directly, if they exist. We only watch their parentl directories if they don't currently exist. This is so that we see fewer events on unrelated files, if a file we care about is in a directory that also contains files we _don't_ care about watching.

Comment (hawkw) [reply proxy/src/fs_watch.rs]: Sorry if my earlier comment wasn't clear; by "when starting a watch", I meant when starting a new _inotify_ watch, not when the watch stream is created.

File: proxy/src/fs_watch.rs (hunk 13 above)
Comment (hawkw) [reply proxy/src/fs_watch.rs]: I think it's good to have  the timeout, so that we can get better errors out of regressions. Since this touches the fs, I think it's reasonable to treat it as an integration test, and we have similar timeout behaviour in some of our integration tests.

I think a 2-second timeout is fairly reasonable here, but I could make it more generous if you think that's likely to reduce flakiness?

File: proxy/src/fs_watch.rs (hunk 12 above)
Comment (hawkw) [reply proxy/src/fs_watch.rs]: Sorry, what do you mean? I don't see an `item` in scope there?

File: proxy/src/fs_watch.rs (hunk 13 above)
Comment (briansmith) [reply proxy/src/fs_watch.rs]: > I think it's good to have the timeout, so that we can get better errors out of regressions.

I don't think that's worth risking flakiness. If the test is otherwise working but we fail to receive the notifications, that's a major bug either in our code or in Linux, and neither should happen with any likelihood. If they were to happen then we'd need to fix the code to stop the tests from ever stalling.

> I think a 2-second timeout is fairly reasonable here, but I could make it more generous if you think that's likely to reduce flakiness?

IMO we should never have timeouts in tests. That that's something that can also be addresses more generally later. If we really want to keep a timeout then let's make it 30s or so.

File: proxy/src/fs_watch.rs (hunk 12 above)
Comment (briansmith) [reply proxy/src/fs_watch.rs]: I mean, shouldn't there be something like this here:

```rust
let (item, watch) = next_change(&mut rt, watch).unwrap();
assert!(item.is_some());
```

Otherwise, how do we know if the notifications received in the `next_change()` calls below are from the `create_and_write` and not from the `remove_file`?

File: proxy/src/fs_watch.rs (hunk 13 above)
Comment (hawkw) [reply proxy/src/fs_watch.rs]: Okay, I'll make the timeout longer here. I think we ought to eventually have a more general discussion about timeouts in tests, as I think @olix0r has some opinions on that as well.

File: proxy/src/fs_watch.rs (hunk 10 above)
Comment (briansmith) [reply proxy/src/fs_watch.rs]: > We always watch the files we care about directly, if they exist. We only watch their parentl directories if they don't currently exist. This is so that we see fewer events on unrelated files, if a file we care about is in a directory that also contains files we don't care about watching.

In our case, won't the directory we are watching only contain files that we care about? I feel like this is an optimization for a general case that isn't actually helpful for us. I would prefer to always do it one way. If we find we're getting too many notifications IRL then we can always add the optimization later.

File: proxy/src/fs_watch.rs (hunk 12 above)
Comment (hawkw) [reply proxy/src/fs_watch.rs]: Ah, yes, you're right; when I rewrote this test, I think I must've briefly forgot that the filtering out of deletions happens in the TLS-specific code and not here. Will fix.

File: proxy/src/fs_watch.rs (hunk 10 above)
Comment (hawkw) [reply proxy/src/fs_watch.rs]: I made an attempt to rewrite this to only watch directories, but I realised that if we're given a path to a file in the CWD (which seems like a fairly plausible case at least while testing locally), we will still sometimes need to watch file paths rather than dirs, so I think there will end up being _some_ special-casing regardless.

The rewritten code looks like this: 
```rust
        fn add_paths(&mut self) -> Result<(), io::Error> {
            let dir_mask
                = WatchMask::CREATE
                | WatchMask::MODIFY
                | WatchMask::DELETE
                | WatchMask::DELETE_SELF
                | WatchMask::MOVE
                | WatchMask::MOVE_SELF
                | WatchMask::ONLYDIR
                ;
            let file_mask
                = WatchMask::CREATE
                | WatchMask::MODIFY
                | WatchMask::DELETE
                | WatchMask::MOVE
                ;
            for path in &self.paths {
                let canonical = path
                    .canonicalize()
                    .unwrap_or_else(|e| {
                        trace!("canonicalize({:?}): {:?}", &path, e);
                        path.to_path_buf()
                    });
                if let Some(ref parent) = canonical.parent() {
                    // If the path has a parent directory, watch that.
                    self.inotify.add_watch(&parent, dir_mask)?;
                    trace!("watch {:?} (for {:?})", parent, path);
                } else {
                    // Otherwise, we're watching the path directly.
                    self.inotify.add_watch(&canonical, file_mask)?;
                    trace!("watch {:?} (for {:?})", &canonical, path);
                };

            }
            Ok(())
        }
```

Let me know if you prefer that over the current implementation, or can think of any ways around having to special-case _something_.

Comment (briansmith) [reply proxy/src/fs_watch.rs]: > I made an attempt to rewrite this to only watch directories, but I realised that if we're given a path to a file in the CWD (which seems like a fairly plausible case at least while testing locally), we will still sometimes need to watch file paths rather than dirs, so I think there will end up being some special-casing regardless.

I think it's fine to punt on this now. I will file an issue about simplifying it. Basically, I think that we should enforce that these env. vars. to be absolute paths so that the issue of having a directory component of "" goes away. Enforcing them to be absolute paths seems like a good idea anyway. But, I don't want to block landing this on that.
