### PR TITLE
Fix double comma in outbound metrics

### LINKED ISSUE #600: invalid prometheus metrics output in proxy
The `/metrics` endpoint on `conduit-proxy` contains invalid output in the form of repeated commas, preventing Prometheus collection:
```
direction="outbound",,status_code="200"
```
## steps to reproduce

```bash
$ git checkout siggy/prom-scrape
$ DOCKER_TRACE=1 bin/docker-build
$ bin/conduit install | kubectl apply -f -
$ curl https://raw.githubusercontent.com/runconduit/conduit-examples/master/emojivoto/emojivoto.yml | bin/conduit inject - | kubectl apply -f -
$ kubectl -n emojivoto exec -it $(kubectl --namespace=emojivoto get po --selector=app=vote-bot -o jsonpath='{.items[*].metadata.name}') -c conduit-proxy curl localhost:4191/metrics
...
response_total{authority="web-svc.emojivoto:80",direction="outbound",,status_code="200"} 2868
response_total{authority="web-svc.emojivoto:80",direction="outbound",,status_code="500"} 334
```

## further validation

We can also validate the issue via the prometheus targets page:

```
$ kubectl -n conduit port-forward $(kubectl --namespace=conduit get po --selector=conduit.io/control-plane-component=prometheus -o jsonpath='{.items[*].metadata.name}') 9090:9090
$ open http://localhost:9090/targets
```

screen shot 2018-03-21 at 5 51 20 pm

relates to #569, #583

### PR DESCRIPTION
**Pull request by hawkw**
Fixes #600 

The proxy metrics endpoint has a bug where metrics recorded in the outbound direction can contain two commas in a row when no outbound label is present. This occurs because the code for formatting the outbound direction label mistakenly assumed that there would always be a destination pod owner label as well, but the proxy isn't currently aware of the destination's pod owner (waiting for #429). 

I've fixed this issue by moving the place where the comma is output from the `fmt::Display` impl for `RequestLabels` to the `fmt::Display` impl for `OutboudnLabels`. This way, the comma between the `direction` and `dst_*` labels is only output when the `dst_*` label is present. 

This bug made it to master since all of the proxy end-to-end tests for metrics only test the inbound router. I've rectified this issue by adding tests on the outbound router as well (which would fail against the current master due to the double comma bug). I've also added a test that asserts there are no double commas in exported metrics, to protect against regressions to this bug.

### CODE REVIEW

File: proxy/src/telemetry/metrics/prometheus.rs [hunk 1]
```diff
@@ -430,11 +430,11 @@ impl fmt::Display for OutboundLabels {
     fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
         match *self {
             OutboundLabels { namespace: Some(ref ns), dst: Some(ref dst) } =>
-                 write!(f, "dst_namespace=\"{}\",dst_{},", ns, dst),
+                 write!(f, ",dst_namespace=\"{}\",dst_{},", ns, dst),
```
Comment (siggy) [inline proxy/src/telemetry/metrics/prometheus.rs]: does this imply that `dst_namespace` should never be written as the first label, because it's preceded by a comma?

to put it another way, it seems like the safest thing to do is to collect the total set of labels, and do join(",") on them, rather than rely on some kind of implicit ordering.

Comment (hawkw) [reply proxy/src/telemetry/metrics/prometheus.rs]: Theoretically, yeah, you're definitely right, and if I were writing a general-purpose Prometheus client library, that's definitely what I'd do. Here, though, we always know the set of labels on a given metric, so the values are stored in a struct rather than a collection, and this way, we can write the formatted values directly to the `Formatter` (i.e. whatever we're outputting to), rather than having to allocate a vector, put all the label value strings in it, format the labels and values values by allocating more strings, join them with commas (allocating another string) and _then_ write them to the `Formatter`, so this is much more efficient. 

I'll document the potential gotchas relating to comma-ordering in a comment.

Comment (seanmonstar) [reply proxy/src/telemetry/metrics/prometheus.rs]: I actually feel it makes sense for the `Display` implementations to not be so aware of where they are being used. I don't think `OutboundLabels` should know it needs to start with a comma, since if we change the order at some point, then we have a leading comma.

It seems probably better to check something like `outbound_labels.is_empty()` from `RequestLabels`, and add a comma if not.

Comment (hawkw) [reply proxy/src/telemetry/metrics/prometheus.rs]: @seanmonstar sure, that would also work.

Comment (hawkw) [reply proxy/src/telemetry/metrics/prometheus.rs]: @seanmonstar WDYT of a3ae247056c6364b2a484b79421d3bedfd4f4253?
