### PR TITLE
Fix bug where table data wasn't being updated

### LINKED ISSUE #236: Deployments table does not update when new deployments are added
It appears that the table of deployments on the Deployments page in the web UI doesn't add new rows automatically when new deployments are added. For instance:

image

You can see that I've added the web, authors, and books deployments, since they show up in the charts at the top of the page, but they're not showing up in the table.

A hard refresh of the page fixes the issue:

image

### PR DESCRIPTION
**Pull request by rmars**
Also remove unused state initializations.

*Problem*
The state of TabbedMetricsTable wasn't being updated when the metrics were updated.

*Cause*
State doesn't update with props update in the constructor
(https://reactjs.org/docs/react-component.html#constructor)

*Solution*
Don't use the state set in the constructor.

Fixes #236

### CODE REVIEW

File: web/app/js/components/TabbedMetricsTable.jsx [hunk 1]
```diff
@@ -79,14 +79,6 @@ export default class TabbedMetricsTable extends React.Component {
...
     this.api = this.props.api;
-
-    this.state = {
-      timeseries: {},
-      rollup: this.preprocessMetrics(),
-      error: '',
-      pollingInterval: 10000,
-      pendingRequests: false
-    };
   }
```
Comment (franziskagoltz) [inline web/app/js/components/TabbedMetricsTable.jsx]: Just to clarify: we don't need to have a state here with `pollingInterval`, as all parent components have it and will trigger a re-render upon fetching a new interval which will trigger down a new and updated render of `TabbedMetricsTable`, right?

Comment (rmars) [reply web/app/js/components/TabbedMetricsTable.jsx]: correct! we fetch data every pollingInterval in the parent component, and pass the data down as a prop to TabbedMetricTable. When the TabbedMetricsTable receives the new props, it will rerender. 
Previously, we were setting the state based on the props in the constructor - this doesn't update the state when new props are passed in, which is why the table wasn't updating.

Comment (franziskagoltz) [reply web/app/js/components/TabbedMetricsTable.jsx]: wonderful! Thanks for confirming / answering my question! 😻 💫

**Comment by rmars** [comment]
The UpstreamDownstream tables receive metrics as props and pass those down to TabbedMetricsTables, also as props. Each component can decide whether to set its own state upon construction based on the props it receives (or even update the state based on new props, using componentWillReceiveProps). We don't actually change any of the data in the TabbedMetricsTable, so there's no need for it to communicate any changes back to its parents. So we can get away with it being rendered solely on its props. The rollup field doesn't get updated because once the component is constructed with `constructor` it doesn't take into account new Props. It doesn't get overridden with empty data, it just decides not to do anything with the new data.
