### PR TITLE
Remove scheme requirement for api-addr flag in conduit CLI

### LINKED ISSUE #121: conduit CLI --api-addr flag requires scheme in addition to host:port
The `conduit` CLI supports a global `--api-addr` flag for overriding the connection to the Kubernetes API. It's documented in the help message as follows:

```
      --api-addr string      Override kubeconfig and communicate directly with the control plane at host:port (mostly for testing)
```

It appears that that flag now requires the input to be a fully qualified url, including the scheme. Omitting the scheme results in:

```
$ conduit --api-addr 192.168.99.100:8085 stat pods
Error: error creating api client while making stats request: error generating base URL for Kubernetes API from [192.168.99.100:8085/api/v1/]
```

It looks like this behavior changed in #68. We should either fix the help message, or change the behavior back to requiring only host:port. My preference is to go back to not requiring the scheme.

As part of this change, can we also fix the capitalization on the k8s api initializer? `NewK8sAPi` => `NewK8sAPI` | `NewK8sApi`

### PR DESCRIPTION
**Pull request by deebo91**
Conduit CLI has the option of providing a URL for a `--api-addr` flag. This option requires that the URL must contain an http scheme in order to create a Kubernetes API client. This PR removes the scheme restriction and allows for a user to enter both a `host:port` or `scheme://host:port` format

New tests were added to `api_test.go` to capture the scenario and tests were run manually with the CLI to ensure that no regression was introduced.

fixes #121

Signed-off-by: Dennis Adjei-Baah <dennis@buoyant.io>

### CODE REVIEW

File: pkg/k8s/api.go [hunk 1]
```diff
@@ -112,6 +115,10 @@ func NewK8sAPi(shell shell.Shell, k8sConfigFilesystemPathOverride string, apiHos
 
 	if apiHostAndPortOverride == "" {
 		apiHostAndPortOverride = config.Host
+	} else {
+		if !httpPrefix.MatchString(apiHostAndPortOverride) {
+			apiHostAndPortOverride = strings.Join([]string{"https://", apiHostAndPortOverride}, "")
```
Comment (pcalcado) [inline pkg/k8s/api.go]: TIOLI What about a `fmt.SPrintf("https://%s", apiHostAndPortOverride)` here?

File: pkg/k8s/api.go [hunk 2]
```diff
@@ -112,6 +115,10 @@ func NewK8sAPi(shell shell.Shell, k8sConfigFilesystemPathOverride string, apiHos
 
 	if apiHostAndPortOverride == "" {
```
Comment (pcalcado) [inline pkg/k8s/api.go]: TIOLI Considering how this branching is growing, instead of reusing `apiHostAndPortOverride` to hold something that's not really an override I would consider making the return from the `if`, 
e.g.
```golang
if apiHostAndPortOverride == "" {
	return &kubernetesApi{
		apiSchemeHostAndPort: config.Host,
		config:               config,
	}, nil
} else {
    if !httpPrefix.MatchString(apiHostAndPortOverride) {
	    apiHostAndPortOverride = strings.Join([]string{"https://", apiHostAndPortOverride}, "")
	}
	return &kubernetesApi{
		apiSchemeHostAndPort: apiHostAndPortOverride,
		config:               config,
	}, nil
}
```

**Comment by deebo91** [comment]
Thanks @pcalcado  all great suggestions, I will have a commit up soon

**Comment by deebo91** [comment]
@pcalcado I made the changes you suggested but I have some additional questions. For `api_test` I rearranged the test to be _table driven_. I started to think about the use case of including other scheme in the URL e.g. `tcp://`. Should the code be checking for invalid url schemes and throwing an error or should it just prepend https:// and wait for the API to fail with the invalid URL? For example, if we mistakenly send "tcp://1.2.3.4" the `Makek8sAPI` function will just tack on `https://tcp://....`try to connect and then eventually fail since that is an invalid url.

**Comment by pcalcado** [comment]
@deebo91 😍 

> Should the code be checking for invalid url schemes and throwing an error or should it just prepend https:// and wait for the API to fail with the invalid URL?

This is a great question, and, in my experience, it is the exact kind of exploratory thinking that TDD leads to!

It seems like the reasons we'd be prepending the protocol here is for convenience, so I would suggest that we keep it simple and only add it if we see that the supplied URL doesn't contain a scheme (i.e. there's no `://` preceded by a string).

Usually, I would say that we should follow [Postel's Law](https://en.wikipedia.org/wiki/Jon_Postel#Postel's_law) and don't try to guess if the protocol supplied by the user is valid (what if they are running in some weird Cloud vendor's version of Kubernetes that uses a different protocol to connect to the API?). In this case, though, we know that Conduit CLI will only work if the Kubernetes API is exposed via HTTP(S). It feels like a better UX if we just let the user know straight away that the protocol supplied isn't supported—and which ones they should be using—, instead of having them puzzled at a more cryptical error message written by the lower-level HTTP client.

We could then write a table-driven test covering all these scenarios, like the one you wrote, and another test and table that explicitly send in some bad input so that we have documented in tests what happens (e.g. `an error is returned`).

And, because this is freeform user input, don't forget to add some bad input reflecting typos :)

**Comment by deebo91** [comment]
@pcalcado rejiggered the tests to try and capture what you were talking about in your previous comments.

File: pkg/k8s/api_test.go [hunk 3]
```diff
@@ -4,26 +4,86 @@ import (
 	"testing"
 
 	"github.com/runconduit/conduit/pkg/shell"
+	"fmt"
+	"net/url"
 )
 
+type TestFixture struct{
```
Comment (pcalcado) [inline pkg/k8s/api_test.go]: Could this be a `map[string]string`? Usually, by convention, the key is input and the value expected output.

File: pkg/k8s/api_test.go [hunk 4]
```diff
@@ -4,26 +4,86 @@ import (
...
+		}
+	})
 
-		api, err := NewK8sAPi(shell.NewUnixShell(), "testdata/config.test", "https://35.184.231.31")
-		if err != nil {
-			t.Fatalf("Unexpected error starting proxy: %v", err)
+	t.Run("Returns unmodified URL from base URL overridden in construction", func(t *testing.T){
+		/* NewK8sAPI is agnostic to the scheme used for the override API. It is only contains code that conveniently
+		adds the default scheme used to connect with the k8s API (https). Supplying a URL with a scheme other than https
+		should return an unmodified override URL */
```
Comment (pcalcado) [inline pkg/k8s/api_test.go]: TIOLI I wonder if this code comment would be made redundant if we rename the test case to something like `"Doesnt modify base URL if it already has a scheme"`?

File: pkg/k8s/api_test.go [hunk 5]
```diff
@@ -4,26 +4,86 @@ import (
...
+		testData := []TestFixture {
```
Comment (pcalcado) [inline pkg/k8s/api_test.go]: TIOLI I wonder if this code comment would be made redundant if we rename the test case to something like `"Doesnt modify base URL if it already has a scheme"`?

File: pkg/k8s/api_test.go [hunk 6]
```diff
@@ -4,26 +4,86 @@ import (
...
+			testInput: "35.184.231.31",
+			expectedOutput:  fmt.Sprintf("https://35.184.231.31/api/v1/namespaces/%s%s", namespace, extraPath),
+		},
+		{
+			testInput: "http://35.184.231.31",
+			expectedOutput:  fmt.Sprintf("http://35.184.231.31/api/v1/namespaces/%s%s", namespace, extraPath),
+		},
+	}
+
 	t.Run("Returns URL from base URL overridden in construction", func(t *testing.T) {
```
Comment (pcalcado) [inline pkg/k8s/api_test.go]: I'd move the fixtures to inside the test case/`func` as they belong to it. Also, maybe the test name is a bit misleading now as this test is also testing the prepending of `http`?

Comment (deebo91) [reply pkg/k8s/api_test.go]: This is an interesting point, I am now essentially testing two different things in one test which I think violates the principles of unit testing. Do you think adding another test would suffice or would that be overkill?

**Comment by deebo91** [comment]
@klingerf I think my recent change to this PR may have captured the use case you were looking for. I am open to hearing your feedback about the latest change.

File: cli/cmd/root.go [hunk 7]
```diff
@@ -44,8 +44,11 @@ func addControlPlaneNetworkingArgs(cmd *cobra.Command) {
 	cmd.PersistentFlags().StringVar(&apiAddr, "api-addr", "", "Override kubeconfig and communicate directly with the control plane at host:port (mostly for testing)")
 }
 
-func newApiClient(kubeApi k8s.KubernetesApi) (pb.ApiClient, error) {
-	return public.NewExternalClient(controlPlaneNamespace, kubeApi)
+func newPublicAPIClient(api k8s.KubernetesApi, apiAddr string) (pb.ApiClient, error) {
```
Comment (klingerf) [inline cli/cmd/root.go]: Cool, you're definitely on the right track here. I'd like to see this method written as:

```
func newPublicAPIClient() (pb.ApiClient, error) {
	if apiAddr != "" {
		return public.NewInternalClient(apiAddr)
	}

	kubeApi, err := k8s.NewK8sAPI(shell.NewUnixShell(), kubeconfigPath)
	if err != nil {
		return nil, err
	}

	return public.NewExternalClient(controlPlaneNamespace, kubeApi)
}
```

My rationale here is: we don't need to call `k8s.NewK8SAPI` if `apiAddr != ""`. So instead I'd prefer for this method to start with the CLI input strings, and only instantiate objects as needed. And if we're working with the CLI inputs (`apiAddr` and `kubeconfigPath`), then we don't need those passed in as parameters, since they're defined globally in this package.

The other change here is that we should need to pass `apiAddr` as a parameter to `k8s.NewK8sAPI`, since the apiAddr override has already been applied by the time we call that function. See my comments below for changes related to this.

File: cli/cmd/stat.go [hunk 8]
```diff
@@ -56,12 +56,12 @@ The optional [TARGET] option can be either a name for a deployment or pod resour
...
 			}
 		}
-		kubeApi, err := k8s.NewK8sAPi(shell.NewUnixShell(), kubeconfigPath, apiAddr)
+		kubeApi, err := k8s.NewK8sAPI(shell.NewUnixShell(), kubeconfigPath, apiAddr)
 		if err != nil {
 			return err
 		}
 
-		client, err := newApiClient(kubeApi)
+		client, err := newPublicAPIClient(kubeApi, apiAddr)
```
Comment (klingerf) [inline cli/cmd/stat.go]: Following up from the comment above, if you rewrite `newPublicAPIClient` as suggested, then you don't need to call `k8s.NewK8sAPI` here (or in any of the other command methods). You can just replace lines 59-64 with:

```
		client, err := newPublicAPIClient()
```

File: cli/cmd/status.go [hunk 9]
```diff
@@ -31,13 +31,13 @@ problems were found.`,
...
 
-		kubeApi, err := k8s.NewK8sAPi(shell.NewUnixShell(), kubeconfigPath, apiAddr)
+		kubeApi, err := k8s.NewK8sAPI(shell.NewUnixShell(), kubeconfigPath, apiAddr)
 		if err != nil {
 			fmt.Fprintf(os.Stderr, "Error with Kubernetes API: %s\n", err.Error())
 			return statusCheckResultWasError(os.Stdout)
 		}
 
-		conduitApi, err := newApiClient(kubeApi)
+		conduitApi, err := newPublicAPIClient(kubeApi, apiAddr)
```
Comment (klingerf) [inline cli/cmd/status.go]: But the status command is an exception to the rule, since we do actually want to know if the call to `k8s.NewK8sAPI` failed. In that case, I'd suggest rewriting this block of code as:

```
		kubeApi, err := k8s.NewK8sAPI(shell.NewUnixShell(), kubeconfigPath)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Error with Kubernetes API: %s\n", err.Error())
			return statusCheckResultWasError(os.Stdout)
		}

		var conduitApi pb.ApiClient
		if apiAddr != "" {
			conduitApi, err = public.NewInternalClient(apiAddr)
		} else {
			conduitApi, err = public.NewExternalClient(controlPlaneNamespace, kubeApi)
		}
		if err != nil {
			fmt.Fprintf(os.Stderr, "Error with Conduit API: %s\n", err.Error())
			return statusCheckResultWasError(os.Stdout)
		}
```

File: pkg/k8s/api.go [hunk 10]
```diff
@@ -114,7 +114,7 @@ func (kubeapi *kubernetesApi) UrlFor(namespace string, extraPathStartingWithSlas
 	return generateKubernetesApiBaseUrlFor(kubeapi.apiSchemeHostAndPort, namespace, extraPathStartingWithSlash)
 }
 
-func NewK8sAPi(shell shell.Shell, k8sConfigFilesystemPathOverride string, apiHostAndPortOverride string) (KubernetesApi, error) {
+func NewK8sAPI(shell shell.Shell, k8sConfigFilesystemPathOverride string, apiHostAndPortOverride string) (KubernetesApi, error) {
```
Comment (klingerf) [inline pkg/k8s/api.go]: We should be able to remove the `apiHostAndPortOverride` argument to this method.

File: pkg/k8s/api.go [hunk 11]
```diff
@@ -123,7 +123,10 @@ func NewK8sAPi(shell shell.Shell, k8sConfigFilesystemPathOverride string, apiHos
 	}
 
 	if apiHostAndPortOverride == "" {
-		apiHostAndPortOverride = config.Host
+		return &kubernetesApi{
+			apiSchemeHostAndPort: config.Host,
+			config:               config,
+		}, nil
 	}
```
Comment (klingerf) [inline pkg/k8s/api.go]: And then instead of checking `apiHostAndPortOverride` at the end of this method, I'd just return:

```
		return &kubernetesApi{Config: config}, nil
```

I'd like to see one other change in this file as well. Since the override is no longer applied, then I think we can simplify the `kubernetesApi` struck with struct embedding. We can change that struct definition to:

```
type kubernetesApi struct {
	*rest.Config
}
```

And then, wherever we were previously calling `kubeapi.apiSchemeHostAndPort`, we can just call `kubeapi.Host`. Likewise where we were calling `kubeapi.config`, we can use `kubeapi.Config` instead.

File: pkg/k8s/api.go [hunk 12]
```diff
@@ -78,10 +77,10 @@ func (kubeapi *kubernetesApi) checkApiAccess(client *http.Client) *healthcheckPb
 		return checkResult
 	}
 
-	endpointToCheck, err := generateBaseKubernetesApiUrl(kubeapi.apiSchemeHostAndPort)
+	endpointToCheck, err := generateBaseKubernetesApiUrl(kubeapi.Config.Host)
```
Comment (klingerf) [inline pkg/k8s/api.go]: Since `Config` is an embedded struct, you can call `kubeapi.Host` directly here. Same goes for the rest of the `kubeapi.Config.Host` calls in this file.

Comment (deebo91) [reply pkg/k8s/api.go]: woah, that's cool! thanks!
