### PR TITLE
proxy: detect TCP socket hang ups from client or server

### LINKED ISSUE #434: MongoDB connections from injected pods keep growing and growing
Yesterday evening, I injected Conduit v0.3.0 into all my production services so I could observe the system behavior with real traffic (off-peak traffic, but still more than on my test cluster). Everything was running smoothly so I went to bed and woke up early in order to assess the situation before morning rush hour knocked at my services' door.

Conduit itself was still up and running, so were all my services. However, I noticed that my MongoDB database was saturated with connections:

mongo connections

This is very unusual, as the number of active connections to Mongo has always stayed within the 300..500 range. The rise of number of connections started pretty much exactly when I injected Conduit in my services.

In order to fix this, I tried (in that order):

1. "Uninject" Conduit from all the services, confirmed that they were no longer green in Conduit Dashboard, waited a few minutes and the number of Mongo connections did not drop.
2. Restarted all Conduit pods (`kubectl delete po --all -n conduit`), waited a few minutes and the number of Mongo connections did not drop.
3. Step down the primary Mongo node, so another node from the replica set would become primary, forcing all Mongo clients to reconnect. This is what worked.

I was expecting step 1 to work, as my understanding was that the Conduit proxies live as a sidecar within my service pods, so I expected that killing the pods would also kill the proxies, freeing up Mongo connections.

When I saw that it didn't work (after waiting ~5 minutes, to make sure the connections reported by Mongo weren't in some "pending close" TCP state), I thought that it might mean that my understanding of the Conduit architecture was wrong, and the proxies actually lived in the `conduit` namespace pods. So that's why I restarted the Conduit pods in step 2.

But again, I was surprised and confused to observe that the connection count had not dropped after restarting the Conduit pods.

That's why I ended up using brute force and switching the replica set to another primary node.

### PR DESCRIPTION
**Pull request by seanmonstar**
Closes #434

### CODE REVIEW

File: proxy/src/transparency/tcp.rs [hunk 1]
```diff
@@ -71,13 +71,32 @@ impl Proxy {
...
+                        //
+                        // TODO: we could actually try to see if the other
+                        // 'copy' has some bytes it still wants to write,
+                        // and try to write them, but we cannot do that with
+                        // the current `Copy` API. We probably just want to
+                        // implement our own duplex pipe future instead.
+                        //
+                        // However, this case is very unlikely. It'd require
+                        // that one side has closed only their write-side of
+                        // the socket, and is still waiting to read.
```
Comment (briansmith) [inline proxy/src/transparency/tcp.rs]: This doesn't seem that unlikely to me, although I do think it is not super common. `shutdown(SHUT_WR)` allows the operating system to discard/recycle the send buffer and other resources on the side calling `shutdown(SHUT_WR)`; similarly the peer can discard its receive buffer. In the case of (Linux) kernel TLS the encryption (respectively, decryption) key can also be discarded. I don't know how common it is but I don't think we should speculate on that here, so I'd at least remove the last paragraph of the comment.

Regardless, I don't understand why, if we know that `copy()` doesn't do exactly what we want, why are we using `copy()`? Is it difficult to implement the correct thing?

**Comment by seanmonstar** [comment]
> I think we've already solved this in linkerd-tcp, so we can probably reuse that.

Oh awesome! This is definitely what I meant, that we write our own future instead of using `Copy`.

The comment I included suggests that this situation is rare. In your experience, is my comment incorrect?

File: proxy/src/transparency/tcp.rs (hunk 1 above)
Comment (seanmonstar) [reply proxy/src/transparency/tcp.rs]: I originally used `copy` since I didn't think of the half-closed case. Writing a solution isn't overly difficult, but it would require essentially copying the source of the `Copy` future, and augmenting it to be duplex. My gut said this case isn't too common, and so weighed the time to write and test versus fixing this now and filing a new bug.

**Comment by seanmonstar** [comment]
OK, new commit, completely removing the caveat, and implementing our own `Duplex` future which should detect and forward shutdowns.

File: proxy/src/connection.rs [hunk 2]
```diff
@@ -165,10 +164,15 @@ impl io::Write for Connection {
...
 impl AsyncWrite for Connection {
     fn shutdown(&mut self) -> Poll<(), io::Error> {
+        use std::net::Shutdown;
         use self::Connection::*;
 
         match *self {
-            Plain(ref mut t) => t.shutdown(),
+            Plain(ref mut t) => {
+                try_ready!(AsyncWrite::shutdown(t));
+                // tcp shutdown afters
```
Comment (briansmith) [inline proxy/src/connection.rs]: s/afters/after/?

Please expand this comment with an explanation of *why* we're doing this.

In general, it would be good to use complete sentences in comments, so that it is clear(er) if/when a comment is complete.

File: proxy/src/transparency/tcp.rs [hunk 3]
```diff
@@ -1,11 +1,13 @@
...
 use std::time::Duration;
 
-use futures::{future, Future};
+use bytes::{Buf, BufMut};
+use futures::{future, Async, Future, Poll};
 use tokio_connect::Connect;
 use tokio_core::reactor::Handle;
 use tokio_io::{AsyncRead, AsyncWrite};
-use tokio_io::io::copy;
+//use tokio_io::io::copy;
```
Comment (briansmith) [inline proxy/src/transparency/tcp.rs]: Remove this comment.

File: proxy/src/transparency/tcp.rs [hunk 4]
```diff
@@ -71,14 +73,177 @@ impl Proxy {
...
         Box::new(fut)
     }
 }
+
+/// A future piping data bi-directionally to In and Out.
+struct Duplex<In, Out> {
+    in_buf: CopyBuf,
+    in_eof: bool,
+    in_io: In,
+    in_shutdown: bool,
```
Comment (briansmith) [inline proxy/src/transparency/tcp.rs]: The repetition here makes me thing that we should have this be something like:

```rust
struct Duplex<In, Out> {
    in: EndPoint<In>,
    out: EndPOint<Out>,
}

struct EndPoint { // Probably there is a better name for this. 
    buf: CopyBuf,
    eof: bool,
    io: In,
    shutdown: bool,
}
```

Also, are some of these variables mutually exclusive with each other; i.e. should some part of this be an enum that helps enforce a well-typed state machine?

File: proxy/src/transparency/tcp.rs [hunk 5]
```diff
@@ -71,14 +73,177 @@ impl Proxy {
...
+    }
+
+    /// Returns true if the Duplex is completely done.
+    ///
+    /// The future may finish earlier if one side has an error.
+    fn is_done(&self) -> bool {
+        self.in_eof
+            && !self.in_buf.has_remaining()
+            && self.out_eof
+            && !self.out_buf.has_remaining()
```
Comment (briansmith) [inline proxy/src/transparency/tcp.rs]: If we refactor this to remove the duplication like I suggest above then I think this would become something like `self.in.is_done() && self.out.is_done()`.

File: proxy/src/transparency/tcp.rs [hunk 6]
```diff
@@ -71,14 +73,177 @@ impl Proxy {
...
+    Out: AsyncRead + AsyncWrite,
+{
+    type Item = ();
+    type Error = io::Error;
+
+    fn poll(&mut self) -> Poll<Self::Item, Self::Error> {
+        // this is macro because we don't want to actually split the IO, as
+        // that requires a futures 'TryLock'. Instead, so that we can skip
+        // that lock, the Duplex holds the original IO, and this macro
+        // prevents duplication of code.
```
Comment (briansmith) [inline proxy/src/transparency/tcp.rs]: I admit I don't quite understand all of this yet. However, can it be refactored to be more understandable?

In particular, I get that there might be a reason why some code here should be in a macro. But, is there any way to factor out a large amount of this code to be a regular function(s) that is (are) used by the macro, so that we can see clearly in the macro definition what is really motivating the use of a macro and avoiding the use of `TryLock`? Right now it is really unclear (at least to me, somebody who doesn't deal with these things often). In general I think it's good to pull out as much code from macros as possible.

File: proxy/src/transparency/tcp.rs [hunk 7]
```diff
@@ -71,14 +73,177 @@ impl Proxy {
...
-                    .map(|_| ())
+                Duplex::new(tcp_in, tcp_out)
                     .map_err(|e| debug!("tcp error: {}", e))
             });
         Box::new(fut)
     }
 }
+
+/// A future piping data bi-directionally to In and Out.
+struct Duplex<In, Out> {
```
Comment (briansmith) [inline proxy/src/transparency/tcp.rs]: It seems to me that this Duplex struct should be in its own module. If it can't be then let's document why not.

Comment (seanmonstar) [reply proxy/src/transparency/tcp.rs]: It *could* be, but it's basically the entirety of this `tcp` module. Splitting it into another isn't really useful, unless we want to make use of `Duplex` in some completely unrelated code. But I feel that if we do want to do that, a refactor can happen at that time.

**Comment by seanmonstar** [comment]
@briansmith I split the `Duplex` into two `HalfDuplex`es in such a way that a lock wasn't actually needed, and put distinct operations in separate methods. Hopefully it's much clearer what is happening.

**Comment by seanmonstar** [comment]
I've combined the `is_eof` into an `Option<CopyBuf>`. Personally, I'm not sure that it's much better, and dropping the buf on eof was tricker thanks to mutable borrows. Still, I suppose its nice that the memory is freed sooner.

As for the shared buffer: I left it as a TODO. It does seem neat, but its also pretty easy to mess up, and the more-obvious way of doing it can result in accidentally copying bytes from the wrong connection, in the case that a copy was not saved. And the compiler wouldn't be able to catch that.

Having a safer version that the compiler *could* catch is less obvious, but I think investing in it should probably be done when metrics show that it would have a worthy impact.
