### PR TITLE
Remove connect timeouts from Bind

### LINKED ISSUE #491: Connection errors should not propagate as request errors
When the proxy attempts to send a request to an endpoint to which there is no preexisting connection, it establishes the connection lazily. If this connection fails (for instance, due to a timeout or socket error), then this failure can result in the request failing entirely.

Instead, the proxy should attempt to dispatch the request to another endpoint in the balancer, or even to the same endpoint if there is only one endpoint in consideration.  The request should be failed only if there are no endpoints in the balancer or if the bind timeout has expired.

---

An issue currently exists in the proxy where a `Timeout` middleware wrapped in a `Reconnect` middleware (from `tower-reconnect`) can cause a request to be canceled, rather than retrying the connection. This is because `Reconnect` implements **reconnecting** on errors *once the connection is successfully established*, but it intentionally does *not* implement **retrying** the connection when an error occurred *while establishing the connection*.

Since the `Timeout` wraps the connection attempt, the connection timing out produces an error while `Reconnect` is in the `Connecting` state, so the error is propagated rather than retrying the connection.

### PR DESCRIPTION
**Pull request by hawkw**
Currently, the `Reconnect` middleware does not reconnect on connection errors (see  #491) and treats them as request errors. This means that when a connection timeout is wrapped in a `Reconnect`, timeout errors are treated as request errors, and the request returns HTTP 500. Since  this is not the desired behavior, the connection timeouts should be removed, at least until their errors can be handled differently.

This PR removes the connect timeouts from `Bind`, as described in https://github.com/runconduit/conduit/pull/483#issuecomment-369380003.

It removes the `CONDUIT_PROXY_PUBLIC_CONNECT_TIMEOUT_MS` environment variable, but _not_ the `CONDUIT_PROXY_PRIVATE_CONNECT_TIMEOUT_MS` variable, since this is also used for the TCP connect timeouts. If we want also want to remove the TCP connection timeouts, I can do that as well.

Closes #483. Fixes #491.

### CODE REVIEW

**Comment by briansmith** [comment]
This is removing the timeout for external ("public") outbound connections too, right? We already have another timeout that properly handles the Destination service not providing us a name, right? If so, it seems OK to remove this timeout for outbound connections since either the application we're proxying has its own timeout already or it doesn't have a timeout and presumably doesn't want one, and we have no good way to configure this timeout for an application that actually wants us to provide it as a feature. However, why did we add it in the first place, @olix0r?

**Comment by briansmith** [comment]
Incidentally, in https://github.com/runconduit/conduit/pull/483#issuecomment-369380003, when I said "this timeout", I meant specifically the one controlled by `CONDUIT_PROXY_PRIVATE_CONNECT_TIMEOUT_MS`. However, I see that the public timeout is using the same code, so it makes sense to remove it at the same time, unless @olix0r has a reason why we need the public timeout.

I would expect that the public timeout would be more useful than the private timeout because if a particular outbound destination is super slow then we should eventually either give up or try a different outbound destination. But maybe this is better undone for now until the retry and circuit breaking features are properly designed.

**Comment by hawkw** [comment]
@briansmith that's correct. The "connect" timeout is applied in `Bind::bind_service`, which is shared  between the inbound and outbound halves.There's already a separate timeout configured for the total time until binding a service to the name (the Destination service response time + time in the proxy).

**Comment by hawkw** [comment]
I suppose that if we do think having the public connect timeout is valuable, I could also modify `Bind` to only apply the timeout if it's configured to do so?

**Comment by hawkw** [comment]
Okay, I figured out what's going on: `tower-reconnect` only reconnects if the connection was successfully established _and then_ errored. If there was an error _while_ connecting, it propagates the error. The connect timeout occurs during the connection, therefore it does not trigger a reconnect.

So it's not so much a bug in `tower-reconnect` as it is an _interaction_ between reconnect and a timeout wrapped by the reconnect middleware. I'll open an issue on `tower` for figuring out the relationship between reconnects and retries.

**Comment by hawkw** [comment]
I've opened tower-rs/tower#60 to track adding a backoff policy on connect errors to the `tower-reconnect` middleware.

**Comment by hawkw** [comment]
I've also opened issue #491 to track the error fixed by this PR.

**Comment by briansmith** [comment]
> I've opened tower-rs/tower#60 to track adding a backoff policy on connect errors to the tower-reconnect middleware.

As far as that might affect Conduit, I think we should probably have a broader discussion of what we're doing with respect to back-off and retry logic. It seems like it's far from clear what we actually want to do and I think we need a design doc that describes what we're going to do immediately and a migration path towards something better.

**Comment by briansmith** [comment]
So, removing the timeout for the private connection seems to make perfect sense and I have no concerns about that.

Let's think critically about whether or not we want the timeout in the public (external) connections. A point in favor of removing the public timeout is the fact that we don't have a good UX for configuring the timeout. A point against removing the public timeout is that we don't (IIUC) have any garbage collection for unused connections, so if the underlying application has a timeout and closes the outbound connection to the proxy, that will have no effect on whether we close the outbound connection to the external service. However, one could argue that the more general problem of not having garbage collection for unused connections is the real problem and having this particular timeout logic is just a band-aid that helps with a special case, and that it's not worthwhile. However, one could also argue that 0.3.1 is a stability and bug fixing release and we've not had any bug reports about the timeout for the timeout for public connections, so we shouldn't change anything w.r.t. them.

This last point is the strongest one for me: If we're not fixing something we know to be broken, and there are downsides to the change, then let's avoid making the change for 0.3.1. So, I'm included to have us keep the public timeout and remove the private timeout, probably using the technique @hawkw suggested.

I think it would be good to hear from others (@olix0r, @seanmonstar, @carllerche, @hawkw) before scrambling to update the PR, to avoid waffling further.

**Comment by olix0r** [comment]
> A point against removing the public timeout is that we don't (IIUC) have any garbage collection for unused connections, so if the underlying application has a timeout and closes the outbound connection to the proxy, that will have no effect on whether we close the outbound connection to the external service.

I don't think that removing the public timer has any practical downside right now, though I strongly agree that we need to have a larger discussion about lifecycle/resource management moving forward

Specifically, if the proxy attempts to connect to a peer and that peer neither opens nor resets the connection, then we'll hold that connection attempt open until the endpoint is removed from service discovery, at which point the connecting future is dropped...

Currently, if those connections timeout, we'll just try to reestablish them the next time a request is dispatched to that peer.

So, I think this is, operationally, effectively equivalent behavior.

File: proxy/src/lib.rs [hunk 1]
```diff
@@ -187,9 +187,7 @@ where
         let inbound = {
             let ctx = ctx::Proxy::inbound(&process_ctx);
 
-            let bind = bind.clone()
-                .with_connect_timeout(config.private_connect_timeout)
-                .with_ctx(ctx.clone());
+            let bind = bind.clone() .with_ctx(ctx.clone());
```
Comment (briansmith) [inline proxy/src/lib.rs]: NIT: extra space here.

File: proxy/src/lib.rs [hunk 2]
```diff
@@ -229,7 +222,7 @@ where
             let fut = serve(
                 outbound_listener,
                 outgoing,
-                tcp_connect_timeout,
+                config.private_connect_timeout,
```
Comment (briansmith) [inline proxy/src/lib.rs]: This should be `public_connect_timeout`, right? The code previously passed `public_connect_timeout` when constructing the `Bind`. Also, `private_connect_timeout` is the one that's way too low, right?

Comment (briansmith) [reply proxy/src/lib.rs]: Also, assuming this PR is correct, we should probably remove the TCP connect timeout too? That is, I don't know why we'd have a timeout for non-HTTP traffic but not have one for HTTP traffic.

Comment (briansmith) [reply proxy/src/lib.rs]: > Also, assuming this PR is correct, we should probably remove the TCP connect timeout too?

In a follow-up PR, assuming this one is approved, I mean.

**Comment by olix0r** [comment]
@hawkw Can you update the pr summary with a clear problem / solution, as it would be committed?

**Comment by hawkw** [comment]
@olix0r how does it look now?

**Comment by olix0r** [comment]
We configure outbound with:

```rust
config.public_connect_timeout.unwrap_or_else(||Duration::from_millis(300)),
```

If I understand correctly, the outcome of this change is that we always use a 300ms connect timeout now, because this cannot be configured?

---

More generally, I don't think we should enforce connect timeouts on TCP connections -- that's up to the application.

**Comment by seanmonstar** [comment]
> More generally, I don't think we should enforce connect timeouts on TCP connections -- that's up to the application.

Due to the way futures work, we'd need to be careful that the steps between receiving a connection and piping on the other side have polled for read (well, HUP, but we can't ask for that directly at the moment), and then notice that the task was woken up because of the HUP. It's, uh, actually a bit tricky.

**Comment by hawkw** [comment]
@olix0r 
> We configure outbound with:
>
>```rust
>config.public_connect_timeout.unwrap_or_else(||Duration::from_millis(300)),
>```
>
> If I understand correctly, the outcome of this change is that we always use a 300ms connect timeout now, because this cannot be configured?

I added the public connect timeout environment variable back in 26f162541b8995facc9469bc577ad78b6e9fe0d5 as @briansmith requested in https://github.com/runconduit/conduit/pull/487#issuecomment-369732280. It should still be configurable.

> More generally, I don't think we should enforce connect timeouts on TCP connections -- that's up to the application.

@briansmith suggested the TCP connection timeout should be removed in a follow-up PR (https://github.com/runconduit/conduit/pull/487#discussion_r171751339). If we agree that timeouts should be removed from TCP connections, I'm happy to add that change to this PR if yoi'd prefer that.

**Comment by briansmith** [comment]
Yes, let's remember the scope of the problem that we're trying to solve: We're trying to solve the problem that the private timeout is too short. To solve that problem, we're removing the private timeout. It so happens that removing the private timeout is easier to do if we remove the public timeout for HTTP too, which is the only reason we're touching that timeout here.

If the TCP timeout is problematic for whatever reason, that's a separate problem and should be fixed separately.

File: proxy/src/lib.rs [hunk 3]
```diff
@@ -229,7 +222,8 @@ where
             let fut = serve(
                 outbound_listener,
                 outgoing,
-                tcp_connect_timeout,
+                config.public_connect_timeout
+                    .unwrap_or_else(||Duration::from_millis(300)),
```
Comment (briansmith) [inline proxy/src/lib.rs]: The defaulting for things should happen in Config`, not in the users of `Config`.

Comment (hawkw) [reply proxy/src/lib.rs]: Changed in 675c05b789904c9f90d1fe6598590eb0981a9063

**Comment by briansmith** [comment]
> > More generally, I don't think we should enforce connect timeouts on TCP connections -- that's up to the application.
> 
> Due to the way futures work, we'd need to be careful that the steps between receiving a connection and piping on the other side have polled for read (well, HUP, but we can't ask for that directly at the moment), and then notice that the task was woken up because of the HUP. It's, uh, actually a bit tricky.

@seanmonstar, @olix0r, and I discussed this today in the context of a 0.3.1 status discussion. @seanmonstar is going to file a new issue regarding his concerns and suggesting a better way to handle the issue in the long term.

**Comment by seanmonstar** [comment]
I've filed https://github.com/runconduit/conduit/issues/511 for TCP connect timeouts.
