### PR TITLE
Don't panic on stats that aren't included in StatAllResourceTypes

### LINKED ISSUE #1151: go panic on `conduit stat ns`
On master, when I run `conduit stat ns`, I get a `panic: runtime error: slice bounds out of range` error.

```
 (master) $ go run cli/main.go stat ns --kubeconfig ~/.kube/config --api-addr localhost:8085
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/runconduit/conduit/cli/cmd.renderStats(0xc420076580, 0x1de0155, 0xa, 0xc42003b490, 0x0, 0x0)
	/Users/mars/workspace/go/src/github.com/runconduit/conduit/cli/cmd/stat.go:146 +0x217
github.com/runconduit/conduit/cli/cmd.requestStatsFromAPI(0x1efa760, 0xc420076560, 0xc420346ea0, 0xc42003b490, 0xc420346ea0, 0x0, 0x0, 0x1e681e0)
	/Users/mars/workspace/go/src/github.com/runconduit/conduit/cli/cmd/stat.go:136 +0x20b
github.com/runconduit/conduit/cli/cmd.newCmdStat.func1(0xc42035afc0, 0xc420348b90, 0x1, 0x5, 0x0, 0x0)
	/Users/mars/workspace/go/src/github.com/runconduit/conduit/cli/cmd/stat.go:105 +0x1d0
github.com/runconduit/conduit/vendor/github.com/spf13/cobra.(*Command).execute(0xc42035afc0, 0xc420348b40, 0x5, 0x5, 0xc42035afc0, 0xc420348b40)
	/Users/mars/workspace/go/src/github.com/runconduit/conduit/vendor/github.com/spf13/cobra/command.go:698 +0x46d
github.com/runconduit/conduit/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x264b680, 0x0, 0xc4201e7f68, 0x1b60eba)
	/Users/mars/workspace/go/src/github.com/runconduit/conduit/vendor/github.com/spf13/cobra/command.go:783 +0x2e4
github.com/runconduit/conduit/vendor/github.com/spf13/cobra.(*Command).Execute(0x264b680, 0xc4201e7f78, 0xc4200ba058)
	/Users/mars/workspace/go/src/github.com/runconduit/conduit/vendor/github.com/spf13/cobra/command.go:736 +0x2b
main.main()
	/Users/mars/workspace/go/src/github.com/runconduit/conduit/cli/main.go:10 +0x2d
exit status 2
```

### PR DESCRIPTION
**Pull request by rmars**
*Problem*
When we run `conduit stat ...`, the `writeStatsToBuffer` function would go through `StatAllResourceTypes` and print all the resources that were there. `namespaces` is not in `StatAllResourceTypes` however, so no stats are written to the buffer. This causes the buffer length to be 0, which causes a panic when we try to do `out := string(buffer.Bytes()[padding:])`

This bug was introduced by https://github.com/runconduit/conduit/pull/1088/files

*Solution*
Fix `writeStatsToBuffer` to not depend on what resources are in `StatAllResourceTypes`.
Also add a `stat` test that would fail on current master. We do already have an integration test for stat, but no unit tests.

Fixes #1151

### CODE REVIEW

File: cli/cmd/stat.go [hunk 1]
```diff
@@ -224,19 +224,21 @@ func writeStatsToBuffer(resp *pb.StatSummaryResponse, reqResourceType string, w
 	}
 
 	lastDisplayedStat := true // don't print a newline after the final stat
```
Comment (siggy) [inline cli/cmd/stat.go]: can you move `lastDisplayedStat` under `case k8s.All`?
also tioli: i struggled to parse the meaning of this variable, does `firstDisplayedStat` make sense?
```
firstDisplayedStat := true // don't print a newline before the first stat
```

File: cli/cmd/stat_test.go [hunk 2]
```diff
@@ -0,0 +1,37 @@
...
+			t.Fatalf("Unexpected error: %v", err)
+		}
+
+		output, err := requestStatsFromAPI(mockClient, req, options)
+		if err != nil {
+			t.Fatalf("Unexpected error: %v", err)
+		}
+
+		if output != expectedOutput {
+			t.Fatalf("Wrong output:\n expected: \n%v\n, got: \n%v", expectedOutput, output)
```
Comment (klingerf) [inline cli/cmd/stat_test.go]: Tiny nit: since `expectedOutput` and `output` are both strings, you could use a more specific format string here:

```
t.Fatalf("Wrong output:\n expected: \n%s\n, got: \n%s", expectedOutput, output)
```

File: test/stat/stat_test.go [hunk 3]
```diff
@@ -46,13 +46,14 @@ var controllerDeployments = []string{"controller", "grafana", "prometheus", "web
 // requesting, and the test will pass.
 func TestCliStatForConduitNamespace(t *testing.T) {
 
+	// test `conduit stat deploy -n <namespace>`
```
Comment (klingerf) [inline test/stat/stat_test.go]: Rather than adding comments, I'd prefer to split this into two separate tests.

```
	t.Run("test conduit stat deploy", func(t *testing.T) {
		...
	})

	t.Run("test conduit stat namespace", func(t *testing.T) {
		...
	})
```

File: test/stat/stat_test.go [hunk 4]
```diff
@@ -69,19 +70,67 @@ func TestCliStatForConduitNamespace(t *testing.T) {
...
+
+		rowStats, err := parseRows(out, 2, true)
+		if err != nil {
+			return err
+		}
+
+		conduitNsFound := false
+		emojivotoNsFound := false
+		for _, row := range rowStats {
+			if row.name == "emojivoto" {
```
Comment (klingerf) [inline test/stat/stat_test.go]: `emojivoto` isn't deployed to the test environment by default, so we can't assume that it's there. I think we could simplify this test a bit and make it more reliable by only checking for stats for the namespace where conduit is deployed, rather than contending with all namespaces. Something like:

```
t.Run("test conduit stat namespace", func(t *testing.T) {
	err := TestHelper.RetryFor(20*time.Second, func() error {
		out, err := TestHelper.ConduitRun("stat", "ns", TestHelper.GetConduitNamespace())
		if err != nil {
			t.Fatalf("Unexpected stat error: %v", err)
		}

		rowStats, err := parseRows(out, 1)
		if err != nil {
			return err
		}

		return validateRowStats(TestHelper.GetConduitNamespace(), rowStats, "4/4")
	})
	if err != nil {
		t.Fatal(err.Error())
	}
})
```

That would also allow you to undo most of the changes that you made in the `parseRows` func. And it allows you to use the `validateRowStats` func for validating namespace stats in addition to deploy stats. You would need to update that func to parameterize the expected mesh count, however, since it won't be the same for conduit deploys ("1/1") and the conduit namespace ("4/4"):

```
func validateRowStats(name string, rowStats map[string]*rowStat, expectedMeshCount string) error {
```

Comment (rmars) [reply test/stat/stat_test.go]: ah whoops! I assumed it was. Yeah, it's probably a good idea to just check the installed conduit namespace!
