### PR TITLE
proxy: Fall back to plaintext communication when a TLS handshake fails

### LINKED ISSUE #1084: The proxy should fall back to plaintext when an endpoint isn't ready for TLS
See also https://github.com/runconduit/conduit/issues/1029#issuecomment-395553126.

The proxy should detect the error returned by another proxy which isn't ready for TLS communication (i.e. it has yet to receive its CA cert and keypair). When the peer isn't ready for TLS, the proxy should communicate with it over a plaintext connection instead.

When our TLS implementation has been validated, we should stop doing this.

### PR DESCRIPTION
**Pull request by hawkw**
This branch modifies the proxy's logic for opening a connection so
that when an attempted TLS handshake fails, the proxy will retry that
connection without TLS.

This is implemented by changing the `UpgradeToTls` case in the `Future`
implementation for `Connecting`, so that rather than simply wrapping
a poll to the TLS upgrade future with `try_ready!` (and thus failing
the future if the upgrade future fails), we reset the state of the
future to the `Plaintext` state and continue looping. The `tls_status`
field of the future is changed to `ReasonForNoTls::HandshakeFailed`,
and the `Plaintext` state is changed so that if its `tls_status` is
`HandshakeFailed`, it will no longer attempt to upgrade to TLS when the
laintext connection is successfully established. This also ensures that
any subsequent telemetry events generated by that connection are labeled
with `tls="handshake_failed"`.

Closes #1084 

Signed-off-by: Eliza Weisman <eliza@buoyant.io>

### CODE REVIEW

File: proxy/src/connection.rs [hunk 1]
```diff
@@ -33,10 +35,14 @@ pub fn connect(addr: &SocketAddr,
...
 pub enum Connecting {
     Plaintext {
+        addr: SocketAddr,
         connect: ConnectFuture,
         tls: Option<tls::ConditionalConnectionConfig<tls::ClientConfig>>,
     },
-    UpgradeToTls(tls::UpgradeClientToTls),
+    UpgradeToTls {
+        addr: SocketAddr,
+        upgrading: tls::UpgradeClientToTls
```
Comment (briansmith) [inline proxy/src/connection.rs]: I think this should be named `upgrade` to be consistent with `connect` in the `Plaintext` variant.

File: proxy/src/connection.rs [hunk 2]
```diff
@@ -185,23 +191,64 @@ impl Future for Connecting {
...
+                            // else go wrong?
+                            let handshake_err = if let Some(tls_error) = e
+                                .get_ref()
+                                .and_then(|e| e.downcast_ref::<tls::Error>())
+                            {
+                                warn!(
+                                    "TLS handshake with {:?} failed: {}\
+                                     -> falling back to plaintext",
+                                    addr, tls_error,
+                                );
```
Comment (briansmith) [inline proxy/src/connection.rs]: To be conservative in favor of keeping things working (vs. being secure), I think we should just do the fallback on any error, not just TLS errors.

File: proxy/src/connection.rs [hunk 3]
```diff
@@ -185,23 +191,64 @@ impl Future for Connecting {
...
+                            } else {
+                                false
+                            };
+                            if handshake_err {
+                                // XXX: We can't get the old connection back
+                                // from the failed upgrade future, so we have
+                                // to try reconnecting.
+                                let connect = TcpStream::connect(addr);
+                                // XXX: Should we propagate *why* the handshake
+                                // failed here?
```
Comment (briansmith) [inline proxy/src/connection.rs]: Ideally we would be more specific, but we can fix that in a follow-up.

More concerning to me is: how are we going to report this reason in telemetry? The reason we have a `ClientConfig` in this module instead of a `ClientConfigWatch` is that we had to extract the reason during binding, much earlier than now. Do we have a way to report telemetry based on information we gather this late?

Comment (hawkw) [reply proxy/src/connection.rs]: Any events on the new connection will have the `tls="handshake_failed"` label without any additional changes. Furthermore, I was thinking that (in a subsequent PR) we would change the `Connecting` future to generate a "handshake failed" event as well, which we could use to track a counter of handshake failures (that could be labeled with each individual error type).

Comment (briansmith) [reply proxy/src/connection.rs]: > Any events on the new connection will have the tls="handshake_failed" label without any additional changes. Furthermore, I was thinking that (in a subsequent PR) we would change the Connecting future to generate a "handshake failed" event as well, which we could use to track a counter of handshake failures (that could be labeled with each individual error type).

We have `TransportLabels::tls_status` too, which is set based on whether we'll *attempt* TLS, vs whether the resulting connection used TLS like here. In particular, `TransportLabels::tls_status` for outbound connections is set during binding, based on the value of `tls_status` from the `transport::Ctx`. Do we still need `TransportLabels::tls_status` given this? Or am I misunderstanding something?

Comment (hawkw) [reply proxy/src/connection.rs]: @briansmith that's not entirely correct --- we're still using `TransportLabels::tls_status` here, but in this case, when we fall back, the `tls_status` field is set to `HandshakeFailed`. 

The handshake failed _event_ I'm considering adding would be used for increment a separate counter of transport failures. I suppose we could also implement this counter on every `TransportOpen` event with the `HandshakeFailed` TLS status; maybe that's the better thing to do...

File: proxy/src/connection.rs [hunk 4]
```diff
@@ -252,24 +262,47 @@ impl Future for Connecting {
...
+                        },
+                        Err(e) => {
+                            warn!(
+                                "TLS handshake with {:?} failed: {}\
+                                    -> falling back to plaintext",
+                                self.addr, e,
+                            );
+                            // XXX: We can't get the old connection back
+                            // from the failed upgrade future, so we have
+                            // to try reconnecting.
```
Comment (olix0r) [inline proxy/src/connection.rs]: I don't really follow this comment. If we've tried to send a TLS handshake on a connection that refused it, there's nothing else that can be done with that connection.

File: proxy/src/transport/tls/config.rs [hunk 5]
```diff
@@ -100,6 +100,11 @@ pub enum ReasonForNoTls {
     /// The connection isn't TLS or it is TLS but not intended to be handled
     /// by the proxy.
     NotProxyTls,
+
+    /// We fell back to plaintext because the TLS handshake failed.
+    // TODO: Perhaps this should store some more detailed information on
+    // why the handshake failed...
```
Comment (olix0r) [inline proxy/src/transport/tls/config.rs]: What are the reasons that a handshake can fail? What do we need to do get access to this information?

File: proxy/src/connection.rs (hunk 4 above)
Comment (hawkw) [reply proxy/src/connection.rs]: Okay, I wasn't sure if the socket could be reused. I'll remove this comment.

File: proxy/src/transport/tls/config.rs (hunk 5 above)
Comment (hawkw) [reply proxy/src/transport/tls/config.rs]: This comment is essentially intended as a placeholder to say "I'm working on this in another branch" (#1212 does this). I can remove it if you prefer.

Comment (olix0r) [reply proxy/src/transport/tls/config.rs]: i'm fine with it if there's an immediate followup

**Comment by olix0r** [comment]
This looks fine to me. I'd like to test it before merging

**Comment by hawkw** [comment]
I've done some manual testing of the fallback logic, and it appears to be working correctly. Here's what I did:

Install Conduit (built from the latest commit on the `ver/tls-test` branch)
```
bin/conduit install -v $(bin/root-tag) --tls=optional -c liza-conduit | kubectl apply -f -
```
Inject Emojivoto with Conduit and deploy it:
```
bin/conduit inject -v $(bin/root-tag) --proxy-log-level=info,conduit_proxy=debug,conduit_proxy::connection=trace --tls=optional emojivoto.yml -c liza-conduit | kubectl apply -f -
```

Created a certs secret _only_ for the `vote-bot` deployment, so that it will try TLS, but all handshakes with other pods will fail (as they lack certs).

In the logs from the `vote-bot` pod, we see:

```
vote-bot-68664799bf-fmdbn conduit-proxy DBUG proxy={client=out dst=web-svc.liza-emojivoto:80 proto=Http1 { host: Authority(web-svc.liza-emojivoto:80), was_absolute_form: false }} conduit_proxy::transparency::client client request: method=GET uri=http://web-svc.liza-emojivoto:80/api/list headers={"host": "web-svc.liza-emojivoto:80", "user-agent": "Go-http-client/1.1", "accept-encoding": "gzip"}
vote-bot-68664799bf-fmdbn conduit-proxy TRCE proxy={server=out listen=127.0.0.1:4140 remote=10.48.13.230:55812} conduit_proxy::connection Connecting: state=plaintext; tls=Some(Some(ConnectionConfig { identity: Identity(DnsName(DNSName("web-b4bbcb5b-5gv8v.deployment.liza-emojivoto.conduit-managed.liza-conduit.svc.cluster.local"))), config: ClientConfig }));
vote-bot-68664799bf-fmdbn conduit-proxy TRCE proxy={server=out listen=127.0.0.1:4140 remote=10.48.13.230:55812} conduit_proxy::connection Connecting: state=plaintext; tls=Some(Some(ConnectionConfig { identity: Identity(DnsName(DNSName("web-b4bbcb5b-5gv8v.deployment.liza-emojivoto.conduit-managed.liza-conduit.svc.cluster.local"))), config: ClientConfig }));
vote-bot-68664799bf-fmdbn conduit-proxy TRCE proxy={server=out listen=127.0.0.1:4140 remote=10.48.13.230:55812} conduit_proxy::connection plaintext connection established; trying to upgrade
vote-bot-68664799bf-fmdbn conduit-proxy WARN proxy={server=out listen=127.0.0.1:4140 remote=10.48.13.230:55812} conduit_proxy::connection TLS handshake with V4(10.48.14.228:80) failed: received corrupt message-> falling back to plaintext
vote-bot-68664799bf-fmdbn conduit-proxy TRCE proxy={server=out listen=127.0.0.1:4140 remote=10.48.13.230:55812} conduit_proxy::connection Connecting: state=plaintext; tls=Some(None(HandshakeFailed));
vote-bot-68664799bf-fmdbn conduit-proxy TRCE proxy={server=out listen=127.0.0.1:4140 remote=10.48.13.230:55812} conduit_proxy::connection Connecting: state=plaintext; tls=Some(None(HandshakeFailed));
vote-bot-68664799bf-fmdbn conduit-proxy TRCE proxy={server=out listen=127.0.0.1:4140 remote=10.48.13.230:55812} conduit_proxy::connection plaintext connection established; no TLS (HandshakeFailed)
vote-bot-68664799bf-fmdbn conduit-proxy DBUG proxy={server=out listen=127.0.0.1:4140 remote=10.48.13.230:55812} conduit_proxy::telemetry::sensor::transport client connection open
```

Which implies that we are correctly falling back to plaintext when the handshake fails.

File: proxy/src/connection.rs [hunk 6]
```diff
@@ -252,24 +262,47 @@ impl Future for Connecting {
...
-                    return Ok(Async::Ready(Connection::tls(BoxedIo::new(tls_stream))));
+                ConnectingState::UpgradeToTls(upgrade) => {
+                    match upgrade.poll() {
+                        Ok(Async::NotReady) => return Ok(Async::NotReady),
+                        Ok(Async::Ready(tls_stream)) => {
+                            let conn = Connection::tls(BoxedIo::new(tls_stream));
+                            return Ok(Async::Ready(conn));
+                        },
+                        Err(e) => {
+                            warn!(
```
Comment (briansmith) [inline proxy/src/connection.rs]: Not a blocker: `warn!` is too high of a logging level for this because we expect this to happen a lot initially due to the delay in distributing the certificate secrets. I suggest `debug!`.

File: proxy/src/connection.rs [hunk 7]
```diff
@@ -252,24 +262,47 @@ impl Future for Connecting {
...
+                                "TLS handshake with {:?} failed: {}\
+                                    -> falling back to plaintext",
+                                self.addr, e,
+                            );
+                            let connect = TcpStream::connect(&self.addr);
+                            // TODO: emit a `HandshakeFailed` telemetry event.
```
Comment (briansmith) [inline proxy/src/connection.rs]: Not a blocker: I don't understand if this means that the "is tls" telemetry will be reported correctly for connections that fall back or not. It seems like the current telemetry reports if we are attempted TLS, not if the connection actually is TLS, but maybe I'm just misunderstanding it. I would love to chat about this after this is merged.

Comment (hawkw) [reply proxy/src/connection.rs]: I've done some testing and it seems that you're right, the label is not added correctly. I'm working on addressing that, but I'm going to continue to do so in another branch so that this can be merged.
