### PR TITLE
proxy: detect TLS configuration changes using inotify on Linux

### LINKED ISSUE #369: Automatically reload certificate and private key when they are updated in the filesystem
This is a follow-up to #306. When a new Kubernetes secret with a new private key and/or certificate is distributed to the proxy (through the kubelet), we need to load the new private key and certificate.

Since the private key and certificate will be provided to the proxy through the filesystem (via a filesystem-mapped Kubernetes secret), we can use `inotify` to watch the given paths for changes. It is important to use `inotify` or an equivalent mechanism whenever possible because we don't want to have a polling background thread in normal use. However, in the case that the `inotify` subscription fails, or on platforms without `inotify`, we should have a backup implementation that does polling in a background thread or equivalent.

It will be instructive to study the implementation of similar measures within linkerd, in particular `inotify`-related bugs.

This builds upon #306; #306 needs to be done first.

### LINKED ISSUE #1061: proxy: Test filesystem watching code with a Kubernetes ConfigMap
We should ensure the filesystem watching code added in 7220fb53670e2bfe2d9424d97edcd40d4d839a83 is able to detect changes in a Kubernetes ConfigMap as a volume mount. @klingerf informs me that in the past, we ran into some issues where changes to ConfigMaps don't correctly change the last modified timestamp. This may have been fixed in Kubernetes, so we should do some testing to determine if this works.

### PR DESCRIPTION
**Pull request by hawkw**
This branch adds an inotify-based implementation of filesystem watches
for the TLS config files. On Linux, where inotify is available, this is
used instead of the polling-based code I added in #1056 and #1076.

In order to avoid the issues detecting changes to files in Kubernetes 
ConfigMaps described in #1061, we watch the directory _containing_ the
files we care about rather than the files themselves. I've tested this 
manually in Docker for Mac Kubernetes and can confirm that ConfigMap
changes are detected successfully.

Note that this currently depends on code added to the `inotify` crate in 
my upstream pull request inotify-rs/inotify#103, rather than the version
on crates.io.

Closes #1061. Closes #369.

### CODE REVIEW

**Comment by hawkw** [comment]
@briansmith (et al.) I've rebased this branch onto the _latest_ master, sorry about the briefly messy diff.

File: proxy/src/transport/tls/config.rs [hunk 1]
```diff
@@ -110,27 +168,56 @@ impl CommonSettings {
...
-        self.change_timestamps(interval)
-            .filter_map(move |_|
-                CommonConfig::load_from_disk(&self)
-                    .map_err(|e| warn!("error reloading TLS config: {:?}, falling back", e))
-                    .ok()
-            )
+        use inotify::{Inotify, WatchMask};
+        // NOTE: If we used a less broad watch mask, we could probably avoid
+        //       reloading the certs multiple times when k8s modifies a
+        //       ConfigMap (a multi-step process that we see as a series of
```
Comment (briansmith) [inline proxy/src/transport/tls/config.rs]: References to "ConfigMap" should be "ConfigMap/Secret". The private key and end-entity certificate will be stored in a secret.

File: proxy/src/transport/tls/config.rs [hunk 2]
```diff
@@ -110,27 +168,56 @@ impl CommonSettings {
...
+        //       live in a k8s ConfigMap, and I think false positives are
+        //       much less harmful here than false negatives.
+        let mask = WatchMask::CREATE
+                 | WatchMask::MODIFY
+                 | WatchMask::DELETE
+                 | WatchMask::MOVE
+                 ;
+        let mut inotify = Inotify::init().map_err(Error::InotifyInit)?;
+
+        for path in &self.paths() {
```
Comment (briansmith) [inline proxy/src/transport/tls/config.rs]: I think we should map each path to the parent and then throw away duplicates. In particular, the end-entity certificate and private key will (usually) be in the same directory so there's no reason to watch that directory twice, IIRC.

Comment (briansmith) [reply proxy/src/transport/tls/config.rs]: Also, we should add a note that we do such de-duping to minimize the chances that we trigger the inotify limit.

File: proxy/src/transport/tls/config.rs [hunk 3]
```diff
@@ -110,27 +168,56 @@ impl CommonSettings {
...
+        -> Result<impl Stream<Item = (), Error = ()>, Error>
     {
-        self.change_timestamps(interval)
-            .filter_map(move |_|
-                CommonConfig::load_from_disk(&self)
-                    .map_err(|e| warn!("error reloading TLS config: {:?}, falling back", e))
-                    .ok()
-            )
+        use inotify::{Inotify, WatchMask};
+        // NOTE: If we used a less broad watch mask, we could probably avoid
```
Comment (briansmith) [inline proxy/src/transport/tls/config.rs]: Let's not prefix comments with "NOTE:" and especially let's not indent them with extra spaces.

File: proxy/src/transport/tls/config.rs (hunk 2 above)
Comment (briansmith) [reply proxy/src/transport/tls/config.rs]: > I thought de-duping here would add unnecessary complexity (and, depending on how we do it, allocations). However, it would also avoid making some additional syscalls, so if you think that's valuable, I'd be happy to add it.

I'm not sure if to duplicate is counted against the inotify limit or not. It's not a big deal but I think it would be clearer if we somehow acknowledge that we understand there will be dupes and what we expect to happen in that case.

Comment (hawkw) [reply proxy/src/transport/tls/config.rs]: Okay, will do.

File: proxy/src/transport/tls/config.rs [hunk 4]
```diff
@@ -110,27 +169,70 @@ impl CommonSettings {
...
-                    .ok()
-            )
+        use inotify::{Inotify, WatchMask};
+        // If we used a less broad watch mask, we could avoid reloading the
+        // certs multiple times when k8s modifies a ConfigMap or Secret (a
+        // multi-step process that we see as a series of CREATE, MOVED_TO,
+        // MOVED_FROM, and DELETE events). However, this may not catch changes
+        // if the files we're watching *don't* live in a k8s ConfigMap/Secret,
+        // and I think false positives are much less harmful here than false
+        // negatives.
```
Comment (olix0r) [inline proxy/src/transport/tls/config.rs]: What I get out of the comment is that there's another way to do it that we're not doing... What do I need to understand from this comment to to understand the code that's here?

File: proxy/src/transport/tls/config.rs [hunk 5]
```diff
@@ -110,27 +169,70 @@ impl CommonSettings {
...
+                    .unwrap_or(path.to_path_buf());
+                trace!("will watch {:?} for {:?}", parent, path);
+                path
+            })
+            // Collect the paths into a `HashSet` eliminates any duplicates, to
+            // conserve the number of inotify watches we create.
+            //
+            // We could probably de-dup the iterator without allocating, by
+            // using `Iterator::peekable`, but this function isn't in the hot
+            // path, so this should be fine.
```
Comment (olix0r) [inline proxy/src/transport/tls/config.rs]: Again, what do I need to understand from this comment to make the code clearer? The second half of this seems irrelevant.

File: proxy/src/transport/tls/config.rs [hunk 6]
```diff
@@ -110,27 +169,70 @@ impl CommonSettings {
...
+            inotify.add_watch(path, mask)
+                .map_err(|e| Error::Io(path.to_path_buf(), e))?;
+            trace!("inotify: watch {:?}", path);
+        }
+
+        // Stream the events using `Inotify::into_event_stream` rather than
+        // `Inotify::event_stream`, so that we transfer ownership of the
+        // underlying file descriptor from the `Inotify` struct to the stream.
+        // Otherwise, the `Inotify` would close the fd when we drop it as we
+        // leave this function, rendering returned the stream useless.
```
Comment (olix0r) [inline proxy/src/transport/tls/config.rs]: Again, I read this to describe an alternate method that we're not pursuing. It doesn't help me understand what's actually happening in the code that's implemented here.

File: proxy/src/transport/tls/config.rs [hunk 7]
```diff
@@ -63,17 +64,70 @@ pub enum Error {
...
+    /// reloaded (i.e., they were malformed), nothing is sent.
+    pub fn stream_changes(self, interval: Duration)
+        -> impl Stream<Item = CommonConfig, Error = ()>
+    {
+        // If we're on Linux, first atttempt to start an Inotify watch on the
+        // paths. If this fails, fall back to polling the filesystem.
+        #[cfg(target_os = "linux")]
+        // Explicit type annotation so that the compiler doesn't infer this to
+        // be `impl Stream<...>` (in which case the match arms would have
+        // different types).
```
Comment (olix0r) [inline proxy/src/transport/tls/config.rs]: This comment doesn't make the code any clearer to me.

Comment (hawkw) [reply proxy/src/transport/tls/config.rs]: I thought that, at first glance, the type annotation seemed unnecessary, so I felt like it ought to be documented so readers would understand why it's there?
