### PR TITLE
 Retry k8s watch endpoints on error

### LINKED ISSUE #478: Controller does not start cleanly on GKE
This appears to have changed since the v0.3.0 release.

When I install Conduit on GKE, the pods in the `conduit` namespace restart multiple times before stabilizing and entering the Running state. I'd expect them to not restart at all. For example:

```
$ kubectl -n conduit get po
NAME                          READY     STATUS    RESTARTS   AGE
controller-5b5c6c4846-6nxb2   6/6       Running   3          2m
prometheus-598fc79646-zl2dw   3/3       Running   0          2m
web-85799d759c-vz2bv          2/2       Running   0          2m
```

It's hard to track down which of the containers is causing the pod to restart, but I see this in the proxy-api container's logs:

```
$ kubectl -n conduit logs controller-5b5c6c4846-6nxb2 proxy-api
time="2018-02-28T00:36:17Z" level=info msg="running conduit version git-9ffe8b79"
time="2018-02-28T00:36:17Z" level=info msg="serving scrapable metrics on :9996"
time="2018-02-28T00:36:17Z" level=info msg="starting gRPC server on :8086"
time="2018-02-28T00:36:27Z" level=error msg="Report: rpc error: code = Unavailable desc = all SubConns are in TransientFailure"
time="2018-02-28T00:36:28Z" level=error msg="Report: rpc error: code = Unavailable desc = all SubConns are in TransientFailure"
time="2018-02-28T00:36:28Z" level=error msg="Report: rpc error: code = Unavailable desc = all SubConns are in TransientFailure"
...
time="2018-02-28T00:36:57Z" level=error msg="Report: rpc error: code = Unknown desc = ResponseCtx is required"
```

I also see this in the conduit-proxy container's logs:

```
$ kubectl -n conduit logs controller-5b5c6c4846-6nxb2 conduit-proxy
INFO conduit_proxy using controller at HostAndPort { host: DnsName("localhost"), port: 8086 }
INFO conduit_proxy routing on V4(127.0.0.1:4140)
INFO conduit_proxy proxying on V4(0.0.0.0:4143) to None
INFO conduit_proxy::transport::connect "controller-client", DNS resolved DnsName("localhost") to 127.0.0.1
ERR! conduit_proxy::map_err turning service error into 500: Inner(Upstream(Inner(Inner(Error { kind: Inner(Error { kind: Proto(INTERNAL_ERROR) }) }))))
WARN conduit_proxy::control::telemetry "controller-client", controller error: Grpc(Status { code: Unavailable })
ERR! conduit_proxy::map_err turning service error into 500: Inner(Upstream(Inner(Inner(Error { kind: Inner(Error { kind: Proto(INTERNAL_ERROR) }) }))))
ERR! conduit_proxy::map_err turning service error into 500: Inner(Upstream(Inner(Inner(Error { kind: Inner(Error { kind: Proto(INTERNAL_ERROR) }) }))))
WARN conduit_proxy::control::telemetry "controller-client", controller error: Grpc(Status { code: Unavailable })
ERR! conduit_proxy::map_err turning service error into 500: Inner(Upstream(Inner(Inner(Error { kind: Inner(Error { kind: Proto(INTERNAL_ERROR) }) }))))
ERR! conduit_proxy::map_err turning service error into 500: Inner(Upstream(Inner(Inner(Error { kind: Inner(Error { kind: Proto(INTERNAL_ERROR) }) }))))
WARN conduit_proxy::control::telemetry "controller-client", controller error: Grpc(Status { code: Unavailable })
ERR! conduit_proxy::map_err turning service error into 500: Inner(Upstream(Inner(Inner(Error { kind: Inner(Error { kind: Proto(INTERNAL_ERROR) }) }))))
WARN conduit_proxy::control::telemetry "controller-client", controller error: Grpc(Status { code: Unknown })
```

If I had to guess, I think these errors are likely a result of the go processes trying to route traffic before the proxy has initialized, and this behavior changed in #365.

Here's the version I'm testing against:

```
$ ./bin/conduit version
Client version: git-9ffe8b79
Server version: git-9ffe8b79
```

### PR DESCRIPTION
**Pull request by dadjeibaah**
Shortly after conduit is installed in k8s environment. The control plane component that establishes a watch endpoint with k8s run in to networking issues during proxy initialization. During failure, each watcher fails to retry its connection to k8s watch endpoint which leads to timeouts and eventually, multiple controller pod restarts. 

This PR adds retry logic to each "watch" enabled package.

fixes #478 

Signed-off-by: Dennis Adjei-Baah <dennis@buoyant.io>

### CODE REVIEW

File: controller/k8s/pods.go [hunk 1]
```diff
@@ -46,7 +46,7 @@ func NewPodIndex(clientset *kubernetes.Clientset, index cache.IndexFunc) (*PodIn
 
 func (p *PodIndex) Run() error {
 	go p.reflector.ListAndWatch(p.stopCh)
-	return newWatcher(p.reflector, podResource).run()
+	return newWatcher(p.reflector, podResource, p.reflector.ListAndWatch, p.stopCh).run()
```
Comment (klingerf) [inline controller/k8s/pods.go]: Since you're passing `p.reflector.ListAndWatch` into the `newWatcher` function now, you don't need to call it here on line 48. As written, the `ListAndWatch` function will be called twice: once line 48, and again on line 47 in watcher.go. I'd just remove the call on line 48 in this file:

```
func (p *PodIndex) Run() error {
	return newWatcher(p.reflector, podResource, p.reflector.ListAndWatch, p.stopCh).run()
}
```

File: controller/k8s/replicasets.go [hunk 2]
```diff
@@ -47,7 +47,7 @@ func NewReplicaSetStore(clientset *kubernetes.Clientset) (*ReplicaSetStore, erro
 
 func (p *ReplicaSetStore) Run() error {
 	go p.reflector.ListAndWatch(p.stopCh)
-	return newWatcher(p.reflector, replicaSetResource).run()
+	return newWatcher(p.reflector, replicaSetResource, p.reflector.ListAndWatch, p.stopCh).run()
```
Comment (klingerf) [inline controller/k8s/replicasets.go]: Same comment here as above -- no need to call `ListAndWatch` in this file.

```
func (p *ReplicaSetStore) Run() error {
	return newWatcher(p.reflector, replicaSetResource, p.reflector.ListAndWatch, p.stopCh).run()
}
```

File: controller/k8s/watcher.go [hunk 3]
```diff
@@ -36,6 +41,18 @@ func (w *watcher) run() error {
 	initialized := make(chan struct{}, 1)
 	defer close(initialized)
 
+	if w.watchInit != nil {
```
Comment (klingerf) [inline controller/k8s/watcher.go]: It will simplify the code if we assume that `watchInit` is always provided and never nil. Let's just remove this nil check.

File: controller/k8s/watcher_test.go [hunk 4]
```diff
@@ -26,7 +27,8 @@ func (w *resourceToWatchImpl) SetLastSyncResourceVersion(version string) {
 func TestWatcher(t *testing.T) {
 	t.Run("Returns nil if the resource initializes in the time limit", func(t *testing.T) {
 		resource := &resourceToWatchImpl{}
-		watcher := newWatcher(resource, "resourcestring")
+		stopCh := make(chan struct{}, 1)
+		watcher := newWatcher(resource, "resourcestring", nil, stopCh)
```
Comment (klingerf) [inline controller/k8s/watcher_test.go]: Related to my comment above about removing the nil check -- we should pass in something that's non-nil here. Maybe at the top of this test, where `resourceToWatchImpl` is defined, you could also define:

```
func watchInitializerImpl(_ <-chan struct{}) error {
	return nil
}
```

And then use that here:

```
		watcher := newWatcher(resource, "resourcestring", watchInitializerImpl, stopCh)
```

File: controller/k8s/watcher_test.go [hunk 5]
```diff
@@ -40,7 +42,8 @@ func TestWatcher(t *testing.T) {
 
 	t.Run("Returns error if the watcher does not initialize in the time limit", func(t *testing.T) {
 		resource := &resourceToWatchImpl{}
-		watcher := newWatcher(resource, "resourcestring")
+		stopCh := make(chan struct{}, 1)
+		watcher := newWatcher(resource, "resourcestring", nil, stopCh)
```
Comment (klingerf) [inline controller/k8s/watcher_test.go]:
```
		watcher := newWatcher(resource, "resourcestring", watchInitializerImpl, stopCh)
```

File: controller/k8s/endpoints.go [hunk 6]
```diff
@@ -129,7 +129,7 @@ type informer struct {
 
 func (i *informer) run() error {
 	go i.informer.Run(i.stopCh)
-	return newWatcher(i.informer, endpointResource).run()
+	return newWatcher(i.informer, endpointResource, nil, i.stopCh).run()
```
Comment (klingerf) [inline controller/k8s/endpoints.go]: Ah, it's a bit unfortunate that the method signature for `i.informer.Run` doesn't match the method signature for a `watchInitializer` (it doesn't return `error`). I think we should coerce the `Run` function to match the method signature, and then pass that function as an argument to `newWatcher`. Something like:

```
func (i *informer) run() error {
	initializer := func(stopCh <-chan struct{}) error {
		i.informer.Run(stopCh)
		return nil
	}
	return newWatcher(i.informer, endpointResource, initializer, i.stopCh).run()
}
```

Comment (klingerf) [reply controller/k8s/endpoints.go]: I've noticed that even with this fix it's still possible for the process to exit on startup, but fortunately it exits immediately, which is better than hanging for 30 seconds:

```
  destination:
    ...
    State:          Running
      Started:      Mon, 05 Mar 2018 09:16:17 -0800
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Mon, 05 Mar 2018 09:16:15 -0800
      Finished:     Mon, 05 Mar 2018 09:16:15 -0800
    Ready:          True
    Restart Count:  1
    ...
```

I think it has something to do with our handling of the endpoints watcher that's different from the pods and replicasets watchers. In the long run we should standardize these things, but in the short term I think this is still an ok fix.

File: controller/k8s/pods.go (hunk 1 above)
Comment (dadjeibaah) [reply controller/k8s/pods.go]: Thanks for that, that was an oversight on my part.

File: controller/k8s/watcher.go [hunk 7]
```diff
@@ -36,6 +41,16 @@ func (w *watcher) run() error {
 	initialized := make(chan struct{}, 1)
 	defer close(initialized)
 
+	go func() {
+		for {
+			err := w.watchInit(w.stopCh)
+			if err != nil {
+				log.Errorf("Error establishing watch in [%s watcher]. Retrying", w.resourceType)
+			}
+			time.Sleep(1 * time.Second)
```
Comment (briansmith) [inline controller/k8s/watcher.go]: This doesn't seem great to for a few reasons:

1 I would expect the proxy to take less than 1s to start up, generally, so ideally the initial timeout should be less than 1s.
2. Backoffs intervals should be increasing over time in general. If that is inappropriate here then there should be a comment explaining why.
3. Retrying *forever* seems wrong to me. If we've been doing this for an hour, for example, then can't we be sure that it's failed? Despite failing to work correctly, we'll be seen as running successfully in terms of Kubernetes' pod management utilities (as reported in kubectl, for example), right?

See https://github.com/kubernetes/client-go/blob/2f45bcbf57f0cfde510a33e7d94a4c89955ff17b/util/retry/util.go#L26-L43.

In particular, should we try to use https://github.com/kubernetes/apimachinery/blob/master/pkg/util/wait/wait.go to address these issues?

**Comment by briansmith** [comment]
> Ah, it's a bit unfortunate that the method signature for i.informer.Run doesn't match the method signature for a watchInitializer (it doesn't return error).

See https://github.com/kubernetes/client-go/issues/155. From reading that client-go issue it looks like the informer already handles some errors itself. It would be useful to have a comment describing why we need to have the use of the informer in a retry loop. In particular, it would be useful to give an example of an error that the informer doesn't recover from itself.

**Comment by briansmith** [comment]
Another question I have about our timeout logic: In https://github.com/kubernetes/kubernetes/pull/17074 client-go provided a way for us to configure timeouts for HTTP requests. It seems like here we're implementing another layer of timeout. Would it be better or worse to use the mechanism introduced in https://github.com/kubernetes/kubernetes/pull/17074 for timeouts instead? I don't know if it is better or worse; it just seems strange to implement our own timeout logic when client-go has an API for controlling timeouts.

File: controller/k8s/watcher.go (hunk 7 above)
Comment (dadjeibaah) [reply controller/k8s/watcher.go]: These are good points. The retry for `util.go` looks like is specifically designed for resource conflicts in k8s so it may be difficult to use that for this retry logic.

I like the idea of using the `wait.go` module, I feel that it is more descriptive I would have to try it out to make sure there is no additional level of complexity being added though. On the issue of retrying indefinitely, it is my understanding that the code retries indefinitely within the 30 seconds and then returns an error which eventually will initiate a pod restart. I think kubectl will report the pod  as being in an `Error` state.

**Comment by dadjeibaah** [comment]
@briansmith spent a couple of minutes figuring out whether we can set up timeouts for requests to k8s with watchers. I haven't found anything that leads me to believe that it is possible but I can keep searching. @klingerf is there a way we can set timeouts for watch requests in any of our watch specific code?

**Comment by briansmith** [comment]
> @briansmith spent a couple of minutes figuring out whether we can set up timeouts for requests to k8s with watchers. I haven't found anything that leads me to believe that it is possible but I can keep searching.

IIUC, we are doing something like "loop forever, but maybe get interrupted by a timeout" where the timeout is set to 30 seconds, somewhere. So, that's a different timeout than the HTTP timeout. AFAICT, the "loop forever, but maybe get interrupted by a timeout" is pretty much trying to implement the util.wait package of k8s.io/apimachinery. I think it makes sense to use util.wait instead so that we get the exponential backoff and so we can start with a shorter retry interval (e.g. 100ms), and so we avoid duplicating already-existing code.

Is 30 seconds enough time to wait before giving up? I guess it is possible that the proxy container image needs to be downloaded and that might reasonably take 30+ seconds. Do we want Kubernetes to kill the pod in that case? It would be useful to document the rational for how long we try before we give up with a code comment.

**Comment by dadjeibaah** [comment]
@briansmith 

> I think it makes sense to use util.wait instead so that we get the exponential backoff and so we can start with a shorter retry interval (e.g. 100ms), and so we avoid duplicating already-existing code.

Using `wait.Until` looks almost identical to what we have currently with the added benefit of Backoff and its more descriptive nature. I am not fully opposed to using `Wait` but the code we have doesn't have any additional layers of complexity 

```go
go wait.Until(func() {
		err := w.watchInit(w.stopCh)
		if err != nil {
			log.Errorf("Error establishing watch in [%s watcher]. Retrying", w.resourceType)
		}
	}, 1*time.Second, wait.NeverStop)
```

vs

```go
	go func() {
		for {
			err := w.watchInit(w.stopCh)
			if err != nil {
				log.Errorf("Error establishing watch in [%s watcher]. Retrying", w.resourceType)
			}
			time.Sleep(1 * time.Second)
		}
	}()
```

> Is 30 seconds enough time to wait before giving up? I guess it is possible that the proxy container image needs to be downloaded and that might reasonably take 30+ seconds.

I am not sure if conduit image binary size is  a deciding factor into how long a timeout should be but the docker images for the proxy are relatively small, about 110MB for proxy and the proxy-int.  I can definitely see that a timeout of 30 seconds might be an issue in an error prone, slow network. Do you have other recommendation on what the timeout should be? 50 seconds could be a good number.

**Comment by briansmith** [comment]
> @briansmith
> > I think it makes sense to use util.wait instead so that we get the exponential backoff and so we can start with a shorter retry interval (e.g. 100ms), and so we avoid duplicating already-existing code.
> 
> Using wait.Until looks almost identical to what we have currently with the added benefit of Backoff and its more descriptive nature. I am not fully opposed to using Wait but the code we have doesn't add any additional layers of complexity

The code we have now does have an additional layer of complexity that isn't seen: the 30 second timeout logic that isn't included in what you quoted.

I looked at `wait.Until` and it doesn't actually implement exponential backoff. `wait.ExponentialBackoff` implements the exponential backoff. So one question is, do you want to have exponential backoff or not. It seems to me like we should have some exponential backoff using an exponent like 1.2 or 1.5 or so. If so, then we should switch to wait.ExponentialBackoff.

> > Is 30 seconds enough time to wait before giving up? I guess it is possible that the proxy container image needs to be downloaded and that might reasonably take 30+ seconds.
> 
> Do you have other recommendation on what the timeout should be? 50 seconds could be a good number.

I don't have a specific recommendation. I don't know Kubernetes' behavior. If the timeout is reached and the container exits with a failing exit code, then does it cancel the downloading of the proxy container image? If so, then the timeout has to be pretty long. If all the container images for a pod are downloaded before the pod is attempted to be started, then the timeout is probably better to be shorter.

I also looked at the rest of your PR. One issue that was noted is that some function panics when you would rather it didn't panic. Now, I am not sure what the exact problem we are solving is. My understanding from the description "each watcher fails to retry its connection to k8s" is that sometimes a TCP `connect()` fails immediately when the proxy isn't running yet. If that is the problem, then why is the retry logic wrapped around the entire watcher, instead of just inside a custom dialer? In particular, why not ask client-go to construct an `http.Client` for us and then replace its `DialContext` with one that retries the TCP connect in a loop using `wait.ExponentialBackoff` or equivalent? That seems like it would solve the exact problem we have and avoid the other complexities.

Also, if these containers are going to retry for a long period of time then they are going to be in an unhealthy state for a long period of time during the retries. This makes me think that we also should have readiness and/or liveness probes as described at https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#define-a-liveness-http-request. (Perhaps these probes should be implemented in a separate issue/PR.)

**Comment by dadjeibaah** [comment]
> We should switch to wait.ExponentialBackoff

Sounds like a plan, I will add that to the next commit.

> I don't have a specific recommendation. I don't know Kubernetes' behavior. If the timeout is reached and the container exits with a failing exit code, then does it cancel the downloading of the proxy container image? If so, then the timeout has to be pretty long. If all the container images for a pod are downloaded before the pod is attempted to be started, then the timeout is probably better to be shorter.

I am not entirely sure of how Kubernetes manages image pulls either but from a kubectl describe, it looks like container images are pulled in parallel. Also, a container is only started once the image is successfully pulled. We can increase the timeout to be a minute which might be ample time to download images, even on a slow network (maybe).

```bash
  Type     Reason                 Age               From               Message
  ----     ------                 ----              ----               -------
  Normal   SuccessfulMountVolume  1m                kubelet, minikube  MountVolume.SetUp succeeded for volume "default-token-khhs2"
  Normal   Scheduled              1m                default-scheduler  Successfully assigned web-786647f9b8-r5zzb to minikube
  Normal   Pulling                1m                kubelet, minikube  pulling image "gcr.io/runconduit/proxy-init:v0.1.0"
  Normal   Pulled                 1m                kubelet, minikube  Successfully pulled image "gcr.io/runconduit/proxy-init:v0.1.0"
  Normal   Created                1m                kubelet, minikube  Created container
  Normal   Started                1m                kubelet, minikube  Started container
  Normal   Pulling                1m                kubelet, minikube  pulling image "gcr.io/runconduit/web:v0.1.0"
  Normal   Pulling                1m                kubelet, minikube  pulling image "gcr.io/runconduit/proxy:v0.1.0"
  Normal   Pulled                 1m                kubelet, minikube  Successfully pulled image "gcr.io/runconduit/web:v0.1.0"
  Normal   Started                1m                kubelet, minikube  Started container
  Normal   Pulled                 1m                kubelet, minikube  Successfully pulled image "gcr.io/runconduit/proxy:v0.1.0"
  Normal   Created                1m                kubelet, minikube  Created container
  Normal   Started                46s (x3 over 1m)  kubelet, minikube  Started container
  Warning  BackOff                34s (x4 over 1m)  kubelet, minikube  Back-off restarting failed container
  Normal   Pulled                 19s (x3 over 1m)  kubelet, minikube  Container image "gcr.io/runconduit/web:v0.1.0" already present on machine
  Normal   Created                19s (x4 over 1m)  kubelet, minikube  Created container
```
> I also looked at the rest of your PR. One issue that was noted is that some function panics when you would rather it didn't panic. Now, I am not sure what the exact problem we are solving is. My understanding from the description "each watcher fails to retry its connection to k8s” 

I may need to rethink the description to clarify the issue, the issue was initially described [here](https://github.com/runconduit/conduit/issues/478#issuecomment-369793575). This PR solves an issue where  a watch that makes a call to k8s is started in a separate goroutine. When this goroutine fails because the proxy isn’t ready, the goroutine exits with an error. The main thread is waiting for the above mentioned goroutine to update a resource version, which signifies that it was able contact k8s. Since the k8s watch goroutine is never retried, the main thread waits for the resource version to update but that never happens. The code in this PR captures the err that happens as a result of the k8s goroutine and retries again, ever second or so.

> why not ask client-go to construct an http.Client for us and then replace its DialContextwith one that retries the TCP connect in a loop using wait.ExponentialBackoff or equivalent? That seems like it would solve the exact problem we have and avoid the other complexities.

We could setup retries further down the stack with the http.Client, but it may result in a large refactor. We could accept this as a first pass to help solve the unclean startup in GKE. I could then open a separate issue to address retries at a more specific level rather than around the whole watcher logic. The new issue could also take advantage of the readiness probes you mentioned so we can add some sense of dependency that can help in pod startup.

**Comment by briansmith** [comment]
> I am not entirely sure of how Kubernetes manages image pulls either but from a kubectl describe, it looks like container images are pulled in parallel. Also, a container is only started once the image is successfully pulled. We can increase the timeout to be a minute which might be ample time to download images, even on a slow network (maybe).

The main question I had regarding the image pulling aspect is whether Kubernetes waits for *all* the images to be downloaded before it starts *any* container in the pod, or whether it starts a container in a pod as soon as its own image is ready. To make progress, we can assume we don't need to worry about this and just use a short timeout; i.e. a minute is fine. If the Conduit proxy image is frequently taking over a minute to start then something is very wrong anyway.

> We could setup retries further down the stack with the http.Client, but it may result in a large refactor. 
We could accept this as a first pass to help solve the unclean startup in GKE. I could then open a separate issue to address retries at a more specific level rather than around the whole watcher logic.

Sure, that sounds OK to me. (I believe that putting the retry logic in the DialContext of the http.Client makes the most sense in the long term, if the issue we're solving is really "the proxy isn't ready yet." If we're solving a broader issue with the watches then what we're doing here might be more appropriate.)
 
> The new issue could also take advantage of the readiness probes you mentioned so we can add some sense of dependency that can help in pod startup.

Separately from the issue for putting retry logic in the DialContext (if we even want to), I think we do need to have a separate issue for the readiness probe. Without the readiness probe, AFAICT, when we roll a new deployment of the control plane, Kubernetes will start sending traffic to the new pods before they are ready, causing failures.

**Comment by briansmith** [comment]
According to https://travis-ci.org/runconduit/conduit/jobs/349989577 and my local testing, this PR needs to update Gopkg.lock after you do `dep ensure`.

**Comment by dadjeibaah** [comment]
Thanks, I thought there was something up with travis

File: controller/k8s/watcher.go [hunk 8]
```diff
@@ -36,6 +47,19 @@ func (w *watcher) run() error {
...
+		Duration: durationBetweenBackoff,
+		Factor:   watchBackoffFactor,
+		Steps:    backoffSteps,
+	}, func() (bool, error) {
+		err := w.watchInit(w.stopCh)
+		if err != nil {
+			log.Errorf("Error establishing watch in [%s watcher]. Retrying", w.resourceType)
+			return false, nil
+		}
+		return true, err
```
Comment (klingerf) [inline controller/k8s/watcher.go]: Based on my reading of the [ExponentialBackoff docs](https://github.com/kubernetes/apimachinery/blob/master/pkg/util/wait/wait.go#L182), returning true here will cause us to stop retrying, but we actually want to retry indefinitely, or at least until MaxInt. So I'd change this to:

```
		return false, err
```

File: controller/k8s/watcher_test.go [hunk 9]
```diff
@@ -51,4 +58,34 @@ func TestWatcher(t *testing.T) {
 			t.Fatalf("Expected error, got nil")
 		}
 	})
+	t.Run("Returns error if the watcher does not initialize in the time limit", func(t *testing.T) {
```
Comment (klingerf) [inline controller/k8s/watcher_test.go]: This test name is identical to the preceding test, and it doesn't really reflect what's being tested in this test. I think you want something along the lines of:

> Retries establishing the watch if it fails to establish the first time

File: controller/k8s/watcher_test.go [hunk 10]
```diff
@@ -51,4 +58,34 @@ func TestWatcher(t *testing.T) {
...
+		resource := &resourceToWatchImpl{}
+		var lock sync.RWMutex
+		didRetry := false
```
Comment (klingerf) [inline controller/k8s/watcher_test.go]: The `didRetry` var is going to be set to true the first time `testWatchInit` is called, which happens immediately. So this var being `true` isn't an indication that retries happened. I think you should instead switch to using an int to count the number of function calls, and assert that it has been called the correct number of times before being timed out.

That will also allow you to use an atomic int, which means you don't need to mess around with the mutex inside this test. So I'd rewrite this as:

```
		watchInitCalls := int32(0)
		expectedCalls := int32(3)
		testWatchInit := func(stop <-chan struct{}) error {
			atomic.AddInt32(&watchInitCalls, 1)
			return errors.New("mock error")
		}
```

File: controller/k8s/watcher_test.go [hunk 11]
```diff
@@ -51,4 +58,34 @@ func TestWatcher(t *testing.T) {
...
+
+		testWatchInit := func(stop <-chan struct{}) error {
+			lock.Lock()
+			defer lock.Unlock()
+			didRetry = true
+			return errors.New("mock error")
+		}
+		stopCh := make(chan struct{}, 1)
+		watcher := newWatcher(resource, "resourcestring", testWatchInit, stopCh)
+		watcher.timeout = 1 * time.Second
```
Comment (klingerf) [inline controller/k8s/watcher_test.go]: Related to my comment above, for this test to be meaningful, we need the give the watcher a higher timeout and assert that x number of calls were made within the timeout. I think we should aim for three calls total, which should take 2.5 seconds with the backoff you have configured. So I'd bump this timeout to 3 seconds to be safe:

```
		watcher.timeout = 3 * time.Second
```

File: controller/k8s/watcher_test.go [hunk 12]
```diff
@@ -51,4 +58,34 @@ func TestWatcher(t *testing.T) {
...
+		go func() {
+			time.Sleep(3 * time.Second)
+			resource.SetLastSyncResourceVersion("synced")
+		}()
```
Comment (klingerf) [inline controller/k8s/watcher_test.go]: There's no need to set the last sync resource version as part of this test, since we're just testing to make sure x number of calls happen before the timeout. You can just remove this go func.

File: controller/k8s/watcher_test.go [hunk 13]
```diff
@@ -51,4 +58,34 @@ func TestWatcher(t *testing.T) {
...
+		_ = watcher.run()
+		select {
+		case <-stopCh:
+			lock.Lock()
+			defer lock.Unlock()
+			if !didRetry {
+				t.Fatalf("watchInitializer failed to retry")
```
Comment (klingerf) [inline controller/k8s/watcher_test.go]: And then I'd change this error check to:

```
		case <-stopCh:
			calls := atomic.LoadInt32(&watchInitCalls)
			if calls != expectedCalls {
				t.Fatalf("expected [%d] calls but observed [%d]", expectedCalls, calls)
			}
```

File: controller/k8s/watcher.go [hunk 14]
```diff
@@ -36,6 +47,19 @@ func (w *watcher) run() error {
 	initialized := make(chan struct{}, 1)
 	defer close(initialized)
 
+	go wait.ExponentialBackoff(wait.Backoff{
+		Duration: durationBetweenBackoff,
```
Comment (briansmith) [inline controller/k8s/watcher.go]: `durationBetweenBackoff` (and similar constants?) are only used in this one place. The code would be clearer if their values were just inlined here.

One of the main reasons to use ExponentialBackoff was so that the initial backoff could be shorter than 1 second, so that if we need to retry (which is super common, apparently) we don't have to wait 1 full second to try again.

In particular, some of these containers depend on other control-plane containers. Thus, it seems like these backoff periods could end up stacking on top of each other such that we might have to wait multiple seconds for the control plane to be fully ready. That's what I'm hoping to avoid, by setting the initial duration to be much less than 1 second.

**Comment by briansmith** [comment]
> I'm actually not sure that an exponential backoff is what we want for this feature, and I can try to explain more later, independent of this PR.

That would be great. When I originally asked if we should use exponential backoff, I said we should document why we're not using an exponential backoff in the code, or else we should switch to an exponential backoff if we didn't intend to use a non-exponential backoff.

(Like I mentioned in the comment above, my original suggestion of using an exponential backoff was partially to allow the initial backoff period to be much less than 1 second long, since 1 second seems excessive and seems like it would make the control plane take a long time to start up fully.)

**Comment by dadjeibaah** [comment]
Tests on GKE show that the new retry logic in this PR fixes the unclean startup issue. Logs from the telemetry service show that retries are happening.
```bash
➜  conduit git:(deebo91/clean-controller-startup) kubectl logs controller-6d5c5fd9c7-whp42 telemetry -n dennis1
time="2018-03-07T21:11:48Z" level=info msg="running conduit version git-f9f52daf"
time="2018-03-07T21:11:48Z" level=error msg="[pods watcher] error establishing watch: github.com/runconduit/conduit/controller/k8s/pods.go:31: Failed to list *v1.Pod: Get https://10.51.240.1:443/api/v1/pods?limit=500&resourceVersion=0: dial tcp 10.51.240.1:443: connect: connection refused"
time="2018-03-07T21:11:48Z" level=debug msg="[pods watcher] retrying"
time="2018-03-07T21:11:48Z" level=error msg="[pods watcher] error establishing watch: github.com/runconduit/conduit/controller/k8s/pods.go:31: Failed to list *v1.Pod: Get https://10.51.240.1:443/api/v1/pods?limit=500&resourceVersion=0: dial tcp 10.51.240.1:443: connect: connection refused"
time="2018-03-07T21:11:48Z" level=debug msg="[pods watcher] retrying"
time="2018-03-07T21:11:48Z" level=error msg="[pods watcher] error establishing watch: github.com/runconduit/conduit/controller/k8s/pods.go:31: Failed to list *v1.Pod: Get https://10.51.240.1:443/api/v1/pods?limit=500&resourceVersion=0: dial tcp 10.51.240.1:443: connect: connection refused"
time="2018-03-07T21:11:48Z" level=debug msg="[pods watcher] retrying"
time="2018-03-07T21:11:49Z" level=error msg="[pods watcher] error establishing watch: github.com/runconduit/conduit/controller/k8s/pods.go:31: Failed to list *v1.Pod: Get https://10.51.240.1:443/api/v1/pods?limit=500&resourceVersion=0: dial tcp 10.51.240.1:443: connect: connection refused"
time="2018-03-07T21:11:49Z" level=debug msg="[pods watcher] retrying"
time="2018-03-07T21:11:49Z" level=debug msg="[pods watcher] waiting for initialization"
time="2018-03-07T21:11:49Z" level=error msg="[pods watcher] error establishing watch: github.com/runconduit/conduit/controller/k8s/pods.go:31: Failed to list *v1.Pod: Get https://10.51.240.1:443/api/v1/pods?limit=500&resourceVersion=0: dial tcp 10.51.240.1:443: connect: connection refused"
time="2018-03-07T21:11:49Z" level=debug msg="[pods watcher] retrying"
time="2018-03-07T21:11:49Z" level=debug msg="[pods watcher] waiting for initialization"
time="2018-03-07T21:11:49Z" level=error msg="[pods watcher] error establishing watch: github.com/runconduit/conduit/controller/k8s/pods.go:31: Failed to list *v1.Pod: Get https://10.51.240.1:443/api/v1/pods?limit=500&resourceVersion=0: dial tcp 10.51.240.1:443: connect: connection refused"
time="2018-03-07T21:11:49Z" level=debug msg="[pods watcher] retrying"
time="2018-03-07T21:11:50Z" level=debug msg="[pods watcher] waiting for initialization"
time="2018-03-07T21:11:50Z" level=debug msg="[pods watcher] waiting for initialization"
time="2018-03-07T21:11:51Z" level=info msg="[pods watcher] initialized"
time="2018-03-07T21:11:51Z" level=info msg="[replicasets watcher] initialized"
time="2018-03-07T21:11:51Z" level=info msg="serving scrapable metrics on:9997"
time="2018-03-07T21:11:51Z" level=info msg="starting gRPC server on :8087"
```

Also pods do not restart on container crash
```bash
➜  conduit git:(deebo91/clean-controller-startup) kubectl get pods -n dennis1
NAME                          READY     STATUS    RESTARTS   AGE
controller-6d5c5fd9c7-whp42   6/6       Running   0          33s
grafana-778fc6cfd6-mf665      2/2       Running   0          32s
prometheus-79b4c9f89b-jl6s8   2/2       Running   0          33s
web-64bfc8c654-5ztzp          2/2       Running   0          33s
```
