### PR TITLE
Fix outbound HTTP/1 requests not using Destinations

### LINKED ISSUE #552: Regression: Proxy ignores Host header when deciding whether to use the Destination service to resolve a name
@klingerf traced this regression to 569d6939a799bb0df6bd4053de7d7e8ac6b49ab6 (https://github.com/runconduit/conduit/pull/492). I also independently bisected the regression to that revision.

This code in the `Recognize` implementation of `Outbound` only considers the authority part of the Request URI, and doesn't consider the Host header field value: https://github.com/runconduit/conduit/blob/9cdc485ee42e5d7175f2336b695797c2d4d315ff/proxy/src/outbound.rs#L90-L95

As a consequence, the proxy ignores the `Host` header field when deciding whether to route the resolve the authority with the Destination service or to fall back to SO_ORIGINAL_DST.

It seems like we're expecting `normalize_our_view_of_uri()` to have been called and to have set the authority in the request URI before this code is executed, but that hasn't happened.

I also noticed that it seems wrong that we execute the SO_ORIGINAL_DST logic in two different places. 
In one instance, the `Recognize` implementation for `Outbound` uses SO_ORIGINAL_DST, here: https://github.com/runconduit/conduit/blob/9cdc485ee42e5d7175f2336b695797c2d4d315ff/proxy/src/outbound.rs#L110-L115

That implies that `recognize()` does NOT expect `normalize_our_view_of_uri()` to have been called beforehand. Yet, this contradicts the logic quoted earlier from the same function, which seems to assume that `normalize_our_view_of_uri()` *has* been called. If `normalize_our_view_of_uri()` already been called then it would have already set the authority to the SO_ORIGINAL_DST so we wouldn't need to query it again; see the code in `normalize_our_view_of_uri()`: https://github.com/runconduit/conduit/blob/9cdc485ee42e5d7175f2336b695797c2d4d315ff/proxy/src/transparency/h1.rs#L32-L44

The consequence of this is that we now have the opposite problem of #155: The destination service is never used for any service, so we've effectively disabled load balancing, but now every external (and internal) service is reachable. This is why #155 appears to be fixed; as soon as *this* issue is fixed, #155 will be broken again.

### PR DESCRIPTION
**Pull request by hawkw**
Commit 569d6939a799bb0df6bd4053de7d7e8ac6b49ab6 introduced a regression that caused the proxy to stop using the Destination service for outbound HTTP/1 requests with no authority in the request URI but a valid authority in the `Host:` header. 

The bug is due to some code in `Outbound::recognize` which assumed that a request had already been passed through `normalize_our_view_of_uri`. This was valid at one point while I was writing #492, as URIs were normalized prior to `recognize` and a request `Extension` was used to mark that they had been rewritten, and the host header and request URI could be assumed to be in agreement, but after merging #514 into the dev branch for #492, this behaviour changed and I forgot to update the logic in `recognize`.

I've fixed the issue by adding the logic for routing on `Host:` headers back into `Outbound::recognize`.

@seanmonstar added a test in `discovery.rs`, `outbound_http1_asks_controller_about_host`, which should exercise this case. I've added a couple more unit tests in that file to try and ensure we cover more of the different cases that can occur here.

Fixes #552

### CODE REVIEW

File: proxy/src/outbound.rs [hunk 1]
```diff
@@ -87,12 +88,20 @@ where
...
-        });
+        // The request URI and Host: header have not yet been normalized
+        // by `NormalizeUri`, as we need to know whether the request will
+        // be routed by Host/authority or by SO_ORIGINAL_DST, in order to
+        // determine whether the service is reusable.
+        let local = req.uri().authority_part()
+            .cloned()
+        // Therefore, we need to check the host header as well as the URI
+        // for a valid authority, before we fall back to SO_ORIGINAL_DST.
+            .or_else(|| h1::authority_from_host(req))
```
Comment (briansmith) [inline proxy/src/outbound.rs]: If `h1::authority_from_host()` returns None then we should return None right here because `h1::authority_from_host()` does the `SO_ORIGNAL_DST` logic itself, so if it doesn't return an Authority then we have nothing to work with.

In particular, we don't need the `SO_ORIGINAL_DST` lower in this function any more, since ``h1::authority_from_host()` does that itself, right?

File: proxy/src/outbound.rs [hunk 2]
```diff
@@ -87,12 +88,20 @@ where
...
-        let local = req.uri().authority_part().map(|authority| {
-            FullyQualifiedAuthority::normalize(
-                authority,
-                &self.default_namespace)
-
-        });
+        // The request URI and Host: header have not yet been normalized
+        // by `NormalizeUri`, as we need to know whether the request will
+        // be routed by Host/authority or by SO_ORIGINAL_DST, in order to
+        // determine whether the service is reusable.
```
Comment (briansmith) [inline proxy/src/outbound.rs]: I think you should truncate this comment at `NormalizeUri` and then move the comment "// If we can't fully qualify the authority as a local service,.." here.

**Comment by olix0r** [comment]
I do believe this fix is correct, but as I've dug into this code, I've found some things that I think we can do to improve clarity.  I'm going to make some better sense of this myself and propose a larger change onto this.  We can fall back onto this branch if we need to.

File: proxy/tests/discovery.rs [hunk 3]
```diff
@@ -18,6 +18,21 @@ fn outbound_asks_controller_api() {
     assert_eq!(client.get("/bye"), "bye");
 }
 
+#[test]
+fn outbound_asks_controller_about_authority() {
```
Comment (briansmith) [inline proxy/tests/discovery.rs]: Please factor out the common logic in these tests so that they are easier to review. These tests all look very similar, but there are at least trivial differences, and it isn't clear if the differences are intentional. It's too hard to tell the difference in what each test is testing now.

Some tests have the comment "don't set srv as outbound(), so that SO_ORIGINAL_DST isn't" but this one doesn't. Also this test is formatted differently than the others, which makes things more confusing. If we factor out the commonality we can prevent this.

File: proxy/src/outbound.rs (hunk 1 above)
Comment (olix0r) [reply proxy/src/outbound.rs]: As noted in #557, `h1::authority_from_host` does _not_ handle `SO_ORIGINAL_DST`.

File: proxy/tests/discovery.rs (hunk 3 above)
Comment (hawkw) [reply proxy/tests/discovery.rs]: @briansmith the latest state of #556 should improve this significantly --- i can merge that back onto this branch if you like.
