### PR TITLE
Use canonical k8s names, fix prom labels

### LINKED ISSUE #695: sanitize statsummary resource type argument
Follow up from https://github.com/runconduit/conduit/pull/671#pullrequestreview-109908929

The `statsummary` command takes a resource type as a positional argument, currently `deployment` is supported.

This string is passed into `CanonicalKubernetesNameFromFriendlyName`, which permits variants of `deployment`, such as `deployments`. The bug manifests when a variant like `deployments` is used from the cli, such that the Kubernetes query succeeds, but the Prometheus query fails, as Prometheus expects the Canonical `deployment` label.

### expected behavior / correct input

```bash
$ bin/conduit statsummary deployment -a emojivoto
NAME       MESHED   IN_RPS   IN_SUCCESS   IN_LATENCY_P50   IN_LATENCY_P99
emoji         1/1   2.0rps      100.00%              0ms              0ms
vote-bot      1/1   0.1rps      100.00%              0ms              0ms
voting        1/1   0.9rps      100.00%              0ms              0ms
web           1/1   1.8rps      100.00%              0ms              0ms
```

### expected behavior / invalid k8s string
```bash
$ bin/conduit statsummary foo -a emojivoto
Error: error calling stat with request: cannot find Kubernetes canonical name from friendly name [foo]
```

### unexpected behavior / unsanitized but valid k8s string

```bash
$ bin/conduit statsummary deployments -a emojivoto
NAME       MESHED   IN_RPS   IN_SUCCESS   IN_LATENCY_P50   IN_LATENCY_P99
emoji         1/1   0.0rps        0.00%              0ms              0ms
vote-bot      1/1   0.0rps        0.00%              0ms              0ms
voting        1/1   0.0rps        0.00%              0ms              0ms
web           1/1   0.0rps        0.00%              0ms              0ms
```

### PR DESCRIPTION
**Pull request by siggy**
The new statsummary command accepted friendly k8s names, which worked
for k8s queries, but Prometheus requires a specific key.

Modify the statsummary query to map friendly k8s names to canonical k8s
names when constructing the query. Then during the query, map the
canonical k8s name to a specific Prometheus label.

Fixes #695

Signed-off-by: Andrew Seigner <siggy@buoyant.io>

### CODE REVIEW

File: cli/cmd/stat_summary.go [hunk 1]
```diff
@@ -31,9 +31,12 @@ Valid resource types include:
 
 This command will hide resources that have completed, such as pods that are in the Succeeded or Failed phases.
 If no resource name is specified, displays stats about all resources of the specified RESOURCETYPE`,
-	Example: `   conduit statsummary deployments -a test
-conduit statsummary deployments all -a test
-conduit statsummary deployments hello1 -a test `,
+	Example: `  # Get all deployments in the test namespace.
+  conduit statsummary deployments -a test
+  conduit statsummary deployments all -a test
```
Comment (klingerf) [inline cli/cmd/stat_summary.go]: I realize this wasn't your change, but I don't think this is a valid example of a statsummary command. Or rather, I think this command would only return stats for the "all" deployment in the test namespace, rather than all deployments in the namespace. Maybe we can just remove line 36?

File: controller/api/public/http_server.go [hunk 2]
```diff
@@ -32,7 +32,7 @@ var (
 
 type handler struct {
 	grpcServer          pb.ApiServer
-	k8sClient           *kubernetes.Clientset
+	k8sClient           kubernetes.Interface
```
Comment (klingerf) [inline controller/api/public/http_server.go]: 👍 👍 👍

File: cli/cmd/stat_summary.go (hunk 1 above)
Comment (klingerf) [reply cli/cmd/stat_summary.go]: I checked and it looks like kubectl doesn't have an special treatment for a target of "all", so I think we should remove our support for that:

```
$ kubectl -n conduit get po all
Error from server (NotFound): pods "all" not found
```
