### PR TITLE
Controller: add more destination labels, fix service label

### LINKED ISSUE #668: dst_service label is not a k8s service
The controller returns destination labels like:
```
dst_service="prometheus.conduit.svc.cluster.local:9090"
```

This should instead be
```
dst_service="prometheus"
```

### LINKED ISSUE #718: destination service must add `deployment` label
The destination service currently adds the following labels to destinations:

```
namespace="emojivoto",
pod="voting-7f6d846b56-8sqmc",
```

If this pod is in `deploy/voting`, it should also add:
```
deployment=voting
```

### LINKED ISSUE #719: destination service must add `replication_controller` label
The destination service currently adds the following labels to destinations:

```
namespace="emojivoto",
pod="voting-7f6d846b56-8sqmc",
```

If this pod is in the `rc/voting`, it should also add:
```
replication_controller=voting
```

### LINKED ISSUE #720: destination service must add `replica_set` labels
The destination service currently adds the following labels to destinations:

```
namespace="emojivoto",
pod="voting-7f6d846b56-8sqmc",
```

If this pod is in the `rs/voting-5432`, it should also add:
```
replica_set=voting-5432
```

### LINKED ISSUE #721: destination service must add `daemon_set` labels
The destination service currently adds the following labels to destinations:

```
namespace="emojivoto",
pod="voting-7f6d846b56-8sqmc",
```

If this pod is in the `ds/voting`, it should also add:
```
daemon_set=voting
```

### PR DESCRIPTION
**Pull request by klingerf**
In #654, the destination service's Get response was updated to support the "namespace", "service", and "pod" labels. In this branch I'm adding "deployment", "replicationcontroller", "replicaset", "job", and "daemonset". I'm also modifying the "service" label so that it reflects the actual service name, rather than the fully-qualified host:port for the service.

The updated labels look like:

```
$ ./bin/go-run controller/script/destination-client -path voting-svc.emojivoto.svc.cluster.local:8080
INFO[0000] Add:                                         
INFO[0000] metric_labels: map[namespace:emojivoto service:voting-svc] 
INFO[0000] - 172.17.0.11:8080 - map[deployment:voting pod:voting-7c84f4d97b-w8j9t] 
```

Fixes #668.
Fixes #718.
Fixes #719.
Fixes #720.
Fixes #721.

### CODE REVIEW

File: pkg/k8s/labels.go [hunk 1]
```diff
@@ -57,8 +58,26 @@ const (
 	ProxyVersionAnnotation = "conduit.io/proxy-version"
 )
 
+var ownerLabels = map[string]string{
+	"deployment":            ProxyDeploymentLabel,
+	"replicationcontroller": ProxyReplicationControllerLabel,
+	"replicaset":            ProxyReplicaSetLabel,
+	"job":                   ProxyJobLabel,
+	"daemonset":             ProxyDaemonSetLabel,
+}
```
Comment (siggy) [inline pkg/k8s/labels.go]: for consistency with source labels, can you change these to the following:
```go
	"deployment":             ProxyDeploymentLabel,
	"replication_controller": ProxyReplicationControllerLabel,
	"replica_set":            ProxyReplicaSetLabel,
	"k8s_job":                ProxyJobLabel,
	"daemon_set":             ProxyDaemonSetLabel,
```

for reference:
https://github.com/runconduit/conduit/blob/28d5007cdf0dbd93d50e20aea3e60689ab830a31/doc/proxy-metrics.md#conduit-labels-added-at-collection-time

also, consider making these strings constants, as they also appear in tests.

File: controller/destination/listener.go [hunk 2]
```diff
@@ -76,11 +86,8 @@ func (l *endpointListener) toWeightedAddrSet(endpoints []common.TcpAddress) *pb.
 				log.Errorf("Could not find pod for IP [%s], this IP will be sent with no metric labels.", ipAsString)
 			} else {
 				pod := resultingPods[0]
-				metricLabelsForPod = map[string]string{
-					"pod": pod.Name,
-				}
-
-				namespace = pod.Namespace
```
Comment (siggy) [inline controller/destination/listener.go]: as we were previously getting `namespace` from the `pod`, what do you think about adding a check here validating that each `l.labels["service"] == pod.Namespace` ?

Comment (klingerf) [reply controller/destination/listener.go]: Do you mean `l.labels["namespace"] == pod.Namespace`? We could add this check, but I'm not sure what we'd do in the case that the check fails. The previous implementation returned the namespace of the last addr in the set, but it never validated that all addrs were in the same namespace. The new implementation sets the namespace based off the service id itself, which I think is more correct, so I'm inclined to just leave this.

File: pkg/k8s/labels.go (hunk 1 above)
Comment (klingerf) [reply pkg/k8s/labels.go]: Good catch! I didn't realize that these were derived from the `conduit.io/proxy-*` labels and needed to match. This change was originally suggested in https://github.com/runconduit/conduit/issues/721#issuecomment-379428283, but I've opened #740 to track that separately. In the meantime I've updated to use the existing labels and have added a test.

File: controller/destination/listener.go (hunk 2 above)
Comment (siggy) [reply controller/destination/listener.go]: Yeah, I meant `l.labels["namespace"]`. It did seem strange we were relying on the namespace of the last addr. I suppose if the check ever failed, there's something bigger and unexpected happening. Cool to leave this as is.

File: doc/proxy-metrics.md [hunk 3]
```diff
@@ -60,7 +60,7 @@ The following labels are only applicable on `response_*` metrics.
 The following labels are only applicable if `direction=outbound`.
 
 * `dst_deployment`: The deployment to which this request is being sent.
-* `dst_job`: The job to which this request is being sent.
+* `dst_k8s_job`: The job to which this request is being sent.
```
Comment (siggy) [inline doc/proxy-metrics.md]: 👍

File: pkg/k8s/labels.go [hunk 4]
```diff
@@ -57,8 +59,39 @@ const (
...
+		if labelValue, ok := objectMeta.Labels[label]; ok {
+			labels[toOwnerLabel(label)] = labelValue
+		}
+	}
+	return labels
+}
+
+// toOwnerLabel converts a proxy label to a prometheus label, following the
+// relabel conventions from the prometheus scrape config file
+func toOwnerLabel(proxyLabel string) string {
```
Comment (siggy) [inline pkg/k8s/labels.go]: I think this is good enough for now, but I had expected that the destination service would derive ownership information from Kubernetes, not from labels injected into the pods. This is particularly relevant for things like ReplicaSets, where Conduit has no knowledge of this at deployment inject time, so those labels will never be set by Conduit.

Related, I am re-introducing a `getPodOwner` method into public-api, cribbed from the telemetry service, that will probably do what we need:
https://github.com/runconduit/conduit/blob/813aa0fddcf5a01ea673a7204ebe2da6932ef4a7/controller/api/public/grpc_server.go#L529-L546

```go
func (s *grpcServer) getPodOwner(pod *k8sV1.Pod) (string, error) {
	namespace := pod.Namespace
	if len(pod.GetOwnerReferences()) == 0 {
		return "", fmt.Errorf("Pod %s has no owner", pod.Name)
	}
	parent := pod.GetOwnerReferences()[0]
	if parent.Kind == "ReplicaSet" {
		rs, err := s.replicaSetLister.GetPodReplicaSets(pod)
		if err != nil {
			return "", err
		}
		if len(rs) == 0 || len(rs[0].GetOwnerReferences()) == 0 {
			return namespace + "/" + parent.Name, nil
		}
		return namespace + "/" + rs[0].GetOwnerReferences()[0].Name, nil
	}
	return namespace + "/" + parent.Name, nil
}
```

Comment (klingerf) [reply pkg/k8s/labels.go]: Ok, this makes sense -- I agree that it would be better to get ownership info directly from kubernetes if available. We should create an issue to do this as a follow-up.
