### PR TITLE
Proxy: Completely replace current set of destinations on reconnect

### LINKED ISSUE #573: Proxy gets out of sync with Destination service on reconnects
In the services discovery logic in the proxy (control/discovery.rs), when the connection to the Destination service is broken (indicated by the stream ending), a reconnect is done. Once the reconnect has occurred the controller will send an `Add` message to the proxy giving the current set of endpoints for the service. The proxy merges this set of endpoints into the set it currently has. However, it never removes any entries that weren't in the set; they will stay in its set forever. (This is based purely on my reading of the code.)

Consider this timeline for a service example.namespace.svc.cluster.local:
1. The proxy subscribes to example.namespace.svc.cluster.local.
2. The Destination service responds with Add {1.2.3.4, 5.6.7.8}.
3. The proxy gets disconnected. It will use {1.2.3.4, 5.6.7.8} as the set of destinations indefinitely.
4. The endpoint 1.2.3.4 is removed, e.g. the pod is de-scheduled.
5. The proxy re-subscribes to example.namespace.svc.cluster.local.
6. The Destination service responds with Add {5.6.7.8}
7. The proxy merges {5.6.7.8} into {1.2.3.4, 5.6.7.8}, resulting in {1.2.3.4, 5.6.7.8}.

At point 4 the Destination service is out of sync with Kubernetes since the proxy thinks 1.2.3.4 is a valid endpoint when Kubernetes knows it is not. At point 7 the destination service and the proxy would be out of sync since the proxy thinks 1.2.3.4 is a valid endpoint and the Destination service knows it is not.

One possible solution would be to clear the set of endpoints for a service when we detect that we need to reconnect to the Destination service. However, this would mean that service discovery would completely fail whenever the connection to the Destination service fails, which is bad for uptime.

A better solution would be to clear the set of endpoints for a service when we receive the first message (e.g. Add or NoEndpoints/Reset) from the Destination service after reconnecting, and then process the message. I think @olix0r has some reservations about doing this.

A more elaborate solution would be to have a TTL associated with all entries, and start expiring entries as soon as we disconnect from the Destination service and/or as soon as we reconnect from the Destination, depending on what we want to prioritize.

This is relevant to #155 because a DNS query and response is basically equivalent to connecting to the destination service, doing a single query, getting a single Add message, disconnecting, and then scheduling a reconnect.

We need to decide:
1. When we are disconnected from the destination service, should we expire and remove entries? if so, how.
2. When we reconnect to the destination service and receive a Reset{service_exists=true} message or an Add message, should we immediately remove the old entries from the previous connection, or should we expire them by TTL?

### PR DESCRIPTION
**Pull request by briansmith**
Previosuly, when the proxy was disconnected from the Destination
service and then reconnects, the proxy would not forget old, outdated
entries in its cache of endpoints. If those endpoints had been removed
while the proxy was disconnected then the proxy would never become
aware of that.

Instead, on the first message after a reconnection, replace the entire
set of cached entries with the new set, which may be empty.

Prior to this change, the new test
outbound_destinations_reset_on_reconnect_followed_by_no_endpoints_exists
passed already
but outbound_destinations_reset_on_reconnect_followed_by_add_none
and outbound_destinations_reset_on_reconnect_followed_by_remove_none
failed. Now all these tests pass.

Fixes #573

### CODE REVIEW

**Comment by briansmith** [comment]
This is based on the branch for #631. I will rebase this on master before merging.

I am not sure if there is a better way to write the integration test that avoids the `sleep(...)` and racy logic. /cc @hawkw

**Comment by briansmith** [comment]
If/when we add a DNS-based mechanism, after every DNS query result is merged we'd do `set.reset_on_next_modification();` so that the results from the previous DNS query would replace the current results, since DNS is connectionless & stateless.

File: proxy/src/control/discovery.rs [hunk 1]
```diff
@@ -275,8 +281,8 @@ where
                             // we may already know of some addresses here, so push
                             // them onto the new watch first
                             match set.addrs {
-                                Exists::Yes(ref mut addrs) => {
-                                    for &addr in addrs.iter() {
+                                Exists::Yes(Cache { ref values, reset_on_next_modification: _ }) => {
```
Comment (olix0r) [inline proxy/src/control/discovery.rs]: to confirm i understand what this syntax indicates: this is ignoring the field, and you opted not to use `, ..` for the sake of being explicit?

**Comment by hawkw** [comment]
@briansmith 
> I am not sure if there is a better way to write the integration test that avoids the `sleep(...)` and racy logic. /cc @hawkw

Possibly the mock controller could expose a future that notifies your test that it's been reconnected to, and you could wait on that before continuing, rather than sleeping? But would certainly add some complexity and may not be worth it...

File: proxy/src/control/discovery.rs [hunk 2]
```diff
@@ -391,79 +398,152 @@ impl<T: HttpService<RequestBody = BoxBody, ResponseBody = RecvBody>> Destination
...
+    }
+
+    fn clear<F>(&mut self, on_change: &mut F) where F: FnMut(T, CacheChange) {
+        self.retain(&HashSet::new(), on_change)
+    }
+
+    fn retain<F>(&mut self, to_retain: &HashSet<T>, mut on_change: F)
+        where F: FnMut(T, CacheChange)
+    {
+        for value in self.values.clone().difference(to_retain) {
```
Comment (olix0r) [inline proxy/src/control/discovery.rs]: fwiw, i think we could likely avoid this clone if we switched to IndexSet (instead of HashSet).  not a blocker

File: proxy/src/control/discovery.rs (hunk 1 above)
Comment (briansmith) [reply proxy/src/control/discovery.rs]: Yes, exactly.

**Comment by briansmith** [comment]
I added a commit that adds documentation to `Cache` so that we can more easily remember the intended semantics.

File: proxy/src/control/discovery.rs (hunk 1 above)
Comment (seanmonstar) [reply proxy/src/control/discovery.rs]: Is there a reason this uses a larger match like that, instead of just something like:

```rust
match set.addrs {
    Exists::Yes(ref cache) => {
        for &addr in cache.values.iter() {
        // ....
    }
}
```

File: proxy/tests/discovery.rs [hunk 3]
```diff
@@ -32,6 +34,77 @@ macro_rules! generate_tests {
...
+
+        #[test]
+        #[cfg_attr(not(feature = "flaky_tests"), ignore)]
+        fn outbound_destinations_reset_on_reconnect_followed_by_remove_none() {
+            outbound_destinations_reset_on_reconnect(move || {
+                Some(controller::destination_remove_none())
+            })
+        }
+
+        fn outbound_destinations_reset_on_reconnect<F>(f: F)
```
Comment (seanmonstar) [inline proxy/tests/discovery.rs]: Does this need a `#[test]` attribute? And I guess a `#[cfg_attr(not(feature = "flaky_tests"), ignore)]`, due to the thread sleep flakiness?

File: proxy/src/control/discovery.rs (hunk 2 above)
Comment (seanmonstar) [reply proxy/src/control/discovery.rs]: Hm, is it faster to clone the full hashset and call `difference`, instead of using `HashSet::retain` directly?

```rust
self.values.retain(|val| {
    to_retain.contains(val)
});
```

File: proxy/src/control/discovery.rs (hunk 1 above)
Comment (briansmith) [reply proxy/src/control/discovery.rs]: I agree that's clearer in this context. I'll change it.

File: proxy/src/control/discovery.rs (hunk 2 above)
Comment (briansmith) [reply proxy/src/control/discovery.rs]: We have to call `on_change` for each removal, so we can't use `retain()` unless I'm misunderstanding something.

File: proxy/tests/discovery.rs (hunk 3 above)
Comment (briansmith) [reply proxy/tests/discovery.rs]: > Does this need a #[test] attribute? 

No. `outbound_destinations_reset_on_reconnect()` isn't a test itself. It is a helpful function used by the three tests that are marked `#[test]`.

>  And I guess a #[cfg_attr(not(feature = "flaky_tests"), ignore)], due to the thread sleep flakiness?

Yes, sadly. I'm expecting it will get resolved after we have mock timers or some other mechanism.

File: proxy/src/control/discovery.rs (hunk 2 above)
Comment (seanmonstar) [reply proxy/src/control/discovery.rs]: So, couldn't be this?

```rust
self.values.retain(|val| {
    if !to_retain.contains(val) {
        on_change(*val, CacheChange::Removal);
        false
    } else {
        true
    }
});
```

Comment (briansmith) [reply proxy/src/control/discovery.rs]: OK, gotcha. Thanks!

**Comment by briansmith** [comment]
I've rebased this PR on top of master after the merge of #631 and I've addressed Sean's review comments. @seanmonstar Please take a look. Thanks!

**Comment by briansmith** [comment]
> The CI build stalled installing, so I gave it a kick.

Thanks!
