### PR TITLE
Make build scripts location-agnostic

### LINKED ISSUE #301: fix web app dev build
The instructions for running `web` in `BUILD.md` no longer work. Running `bin/go-run web` from the root of the repo fails because it cannot find the template and static dirs, as the default params assume the process is started from the `web` subdir:

```bash
$ bin/go-run web --help
...
  -static-dir string
    	directory to search for static files (default "app/dist")
  -template-dir string
    	directory to search for template files (default "templates")
```

This results in a null pointer exception, as the `template` var is nil:
https://github.com/runconduit/conduit/blob/a9d4a3d74e6912889a8056a3b788d281720a3fa2/web/srv/server.go#L115

Action items:
1) Update `BUILD.md` with correct build/run instructions:
  ```bash
  cd web
  ../bin/go-run .
  ```
2) Modify `loadTemplate` to return an error if the template is not found:
https://github.com/runconduit/conduit/blob/a9d4a3d74e6912889a8056a3b788d281720a3fa2/web/srv/server.go#L103

### PR DESCRIPTION
**Pull request by siggy**
The build scripts assume they are executed from the root of this repo.
This prevents running scripts from other locations, for example,
`cd web && ../bin/go-run .`.

Modify the build scripts to work regardless of current directory.

Fixes #301

Signed-off-by: Andrew Seigner <siggy@buoyant.io>

### CODE REVIEW

File: bin/_tag.sh [hunk 1]
```diff
@@ -1,4 +1,4 @@
-#!/bin/sh
```
Comment (olix0r) [inline bin/_tag.sh]: we can just remove this! and we can `chmod 644`

File: bin/_gcp.sh [hunk 2]
```diff
@@ -1,4 +1,4 @@
-#!/bin/sh
```
Comment (olix0r) [inline bin/_gcp.sh]: we can just remove this! and we can `chmod 644`

File: bin/_log.sh [hunk 3]
```diff
@@ -1,4 +1,4 @@
-#!/bin/sh
```
Comment (olix0r) [inline bin/_log.sh]: we can just remove this! and we can `chmod 644`

**Comment by siggy** [comment]
yeah, i went back and forth on `basedir` vs `bindir`. switching it back to `bindir`.
