### PR TITLE
Run conduit dashboard on ephemeral port by default

### LINKED ISSUE #291: Stop using port 8001 as the default port for `conduit dashboard`
`kubectl proxy` uses port 8001 as its default. Thus, any time the user is running `kubectl proxy` then `conduit dashboard` will fail, at default settings, since the port will be in use already. A very simple way to prevent this failure more often is to use a port other than 8001 by default. 

Especially now that https://github.com/runconduit/conduit/pull/249 has landed we could probably even use a random port by completely avoid collisions. Whether it makes sense to use a random port or a different fixed port by default depends on whether we want to support the user bookmarking the URL for the proxied dashboard. I don't think we need to support the bookmarking, especially because it is likely that the URLs will change in the future when we add better TLS support to the control plane.

### PR DESCRIPTION
**Pull request by klingerf**
This branch changes the `conduit dashboard`'s default `--port` value to 0, which means that it will start the dashboard on a random ephemeral port.

As part of this change I'm also cleaning up the error message that's printed when conduit is not installed (relates to #289). Previously it would print:

```
$ conduit dashboard -n foo
Failed while checking availability of dashboard: POST to Conduit API endpoint [https://192.168.99.103:8443/api/v1/namespaces/foo/services/http:api:http/proxy/api/v1/SelfCheck] returned HTTP status [404 Not Found]
Conduit web deployment is not installed in your cluster
```

Now it prints:

```
$ conduit dashboard -n foo
Conduit is not running in the "foo" namespace
Install with: conduit install -n foo | kubectl apply -f -
```

Fixes #291.

### CODE REVIEW

File: cli/cmd/dashboard.go [hunk 1]
```diff
@@ -44,12 +44,9 @@ var dashboardCmd = &cobra.Command{
...
 		dashboardAvailable, err := isDashboardAvailable(client)
-		if err != nil {
-			fmt.Fprintf(os.Stderr, "Failed while checking availability of dashboard: %+v\n", err)
-		}
-
-		if !dashboardAvailable {
-			fmt.Fprint(os.Stderr, "Conduit web deployment is not installed in your cluster\n")
+		if err != nil || !dashboardAvailable {
+			fmt.Fprintf(os.Stderr, "Conduit is not running in the \"%s\" namespace\n", controlPlaneNamespace)
+			fmt.Fprintf(os.Stderr, "Install with: conduit install -n %s | kubectl apply -f -\n", controlPlaneNamespace)
```
Comment (briansmith) [inline cli/cmd/dashboard.go]: I think this unrelated change should be removed from this commit. If this is fixing a problem then it should be in a commit that describes the problem being fixed. (In particular, I think this *introduces* a problem: We don't report `err` when `err != nil`. If that's intentional then it should be explained in the new PR's commit message too.)

File: cli/cmd/dashboard.go [hunk 2]
```diff
@@ -97,6 +94,6 @@ func init() {
 
 	// This is identical to what `kubectl proxy --help` reports, `--port 0`
 	// indicates a random port.
-	dashboardCmd.PersistentFlags().IntVarP(&dashboardProxyPort, "port", "p", 8001, "The port on which to run the proxy. Set to 0 to pick a random port.")
+	dashboardCmd.PersistentFlags().IntVarP(&dashboardProxyPort, "port", "p", 0, "The port on which to run the proxy. Set to 0 to pick a random port.")
```
Comment (briansmith) [inline cli/cmd/dashboard.go]: NIT: Since the default is now 0, I would change this message to "When set to 0, a random port will be used."

File: cli/cmd/dashboard.go (hunk 1 above)
Comment (klingerf) [reply cli/cmd/dashboard.go]: This is described in the description for this pull request, as follows:

As part of this change I'm also cleaning up the error message that's printed when conduit is not installed (relates to #289). Previously it would print:

```
$ conduit dashboard -n foo
Failed while checking availability of dashboard: POST to Conduit API endpoint [https://192.168.99.103:8443/api/v1/namespaces/foo/services/http:api:http/proxy/api/v1/SelfCheck] returned HTTP status [404 Not Found]
Conduit web deployment is not installed in your cluster
```

Now it prints:

```
$ conduit dashboard -n foo
Conduit is not running in the "foo" namespace
Install with: conduit install -n foo | kubectl apply -f -
```

**Comment by briansmith** [comment]
LGTM.

(It seems that since you are a project owner, only the specific people you asked to review the PR can approve it, so I can't.)

File: cli/cmd/dashboard.go (hunk 1 above)
Comment (klingerf) [reply cli/cmd/dashboard.go]: @briansmith I see your point about discarding the actual error message in favor of the more user-friendly message. I have updated this branch to log the error at debug level, so that it will still be printed if the `--verbose` flag is used.

For instance, without the `--verbose` flag, it prints:

```
$ conduit dashboard
Conduit is not running in the "conduit" namespace
Install with: conduit install -n conduit | kubectl apply -f -
```

But with the `--verbose` flag:

```
$ conduit dashboard --verbose
DEBU[0000] Expecting Conduit Public API to be served over [https://192.168.99.103:8443/api/v1/namespaces/conduit/services/http:api:http/proxy/api/v1/] 
DEBU[0000] Making gRPC-over-HTTP call to [https://192.168.99.103:8443/api/v1/namespaces/conduit/services/http:api:http/proxy/api/v1/SelfCheck] 
DEBU[0000] Response from [https://192.168.99.103:8443/api/v1/namespaces/conduit/services/http:api:http/proxy/api/v1/SelfCheck] had headers: map[Content-Type:[application/json] Content-Length:[182] Date:[Tue, 20 Feb 2018 18:05:14 GMT]] 
DEBU[0000] gRPC-over-HTTP call returned status [404 Not Found] and content length [182] 
DEBU[0000] Error checking dashboard availability: POST to Conduit API endpoint [https://192.168.99.103:8443/api/v1/namespaces/conduit/services/http:api:http/proxy/api/v1/SelfCheck] returned HTTP status [404 Not Found] 
Conduit is not running in the "conduit" namespace
Install with: conduit install -n conduit | kubectl apply -f -
```

That should at least help with debugging when issues are encountered.
