### PR TITLE
Print error message only when invalid YAML file is used with inject command

### LINKED ISSUE #303: Conduit inject prints the whole YAML file when invalid
What happens: When the YAML is broken, the CLI prints the correct error message but dumps the whole file
What I expected to happen: Just the error message and return `!=0`. I can see that dump being useful but it should only be there if the user has set `--verbose`.

## Reproducing
Given this file:
```yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: get-test      
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: get-test-deploy-injected-1
  namespace: get-test
spec:
  replicas: 1
  selector:
      matchLabels:
        app: get-test
  template:
    metadata:
          labels:
            app: get-test
    spec:
      containers:
      - name: http-to-grpc-two-replicas-c1
        image: buoyantio/bb:v1
        args: ["terminus", "--grpc-server-port", "9090", "--response-text", "c1"]
        ports:
        - containerPort: 9090
      - name: http-to-grpc-two-replicas-c2
        image: buoyantio/bb:v1
        args: ["terminus", "--grpc-server-port", "8080", "--response-text", "c2"]
        ports:
        - containerPort: 9090
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: get-test-deploy-injected-2
  namespace: get-test
spec:
  replicas: 1
  selector:
      matchLabels:
        app: get-test
  template:
      metadata:
            labels:
              app: get-test
    spec:
      containers:
      - name: http-to-grpc-one-replica-c1
        image: buoyantio/bb:v1
        args: ["terminus", "--grpc-server-port", "9090", "--response-text", "c1"]
        ports:
        - containerPort: 9090
      - name: http-to-grpc-one-replica-c2
        image: buoyantio/bb:v1
        args: ["terminus", "--grpc-server-port", "8080", "--response-text", "c2"]
        ports:
        - containerPort: 9090
```

This is the output:
```shell
pcalcado@arbeitsziege.local$ conduit inject test/get/testdata/to_be_injected_application.yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: get-test
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: get-test-deploy-injected-1
  namespace: get-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: get-test
  strategy: {}
  template:
    metadata:
      annotations:
        conduit.io/created-by: conduit/cli git-4156af78
        conduit.io/proxy-version: git-4156af78
      creationTimestamp: null
      labels:
        app: get-test
        conduit.io/control-plane-ns: conduit
    spec:
      containers:
      - args:
        - terminus
        - --grpc-server-port
        - "9090"
        - --response-text
        - c1
        image: buoyantio/bb:v1
        name: http-to-grpc-two-replicas-c1
        ports:
        - containerPort: 9090
        resources: {}
      - args:
        - terminus
        - --grpc-server-port
        - "8080"
        - --response-text
        - c2
        image: buoyantio/bb:v1
        name: http-to-grpc-two-replicas-c2
        ports:
        - containerPort: 9090
        resources: {}
      - env:
        - name: CONDUIT_PROXY_LOG
          value: warn,conduit_proxy=info
        - name: CONDUIT_PROXY_CONTROL_URL
          value: tcp://proxy-api.conduit.svc.cluster.local:8086
        - name: CONDUIT_PROXY_CONTROL_LISTENER
          value: tcp://0.0.0.0:4190
        - name: CONDUIT_PROXY_PRIVATE_LISTENER
          value: tcp://127.0.0.1:4140
        - name: CONDUIT_PROXY_PUBLIC_LISTENER
          value: tcp://0.0.0.0:4143
        - name: CONDUIT_PROXY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: CONDUIT_PROXY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: CONDUIT_PROXY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CONDUIT_PROXY_DESTINATIONS_AUTOCOMPLETE_FQDN
          value: Kubernetes
        image: gcr.io/runconduit/proxy:git-4156af78
        imagePullPolicy: IfNotPresent
        name: conduit-proxy
        ports:
        - containerPort: 4143
          name: conduit-proxy
        resources: {}
        securityContext:
          runAsUser: 2102
      initContainers:
      - args:
        - --incoming-proxy-port
        - "4143"
        - --outgoing-proxy-port
        - "4140"
        - --proxy-uid
        - "2102"
        - --inbound-ports-to-ignore
        - "4190"
        image: gcr.io/runconduit/proxy-init:git-4156af78
        imagePullPolicy: IfNotPresent
        name: conduit-init
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
          privileged: false
status: {}
---
Error: error converting YAML to JSON: yaml: line 14: did not find expected key
Usage:
  conduit inject [flags] CONFIG-FILE

Flags:
      --api-port uint                   port where the Conduit controller is running (default 8086)
  -v, --conduit-version string          tag to be used for conduit images (default "git-4156af78")
      --control-port uint               proxy port to use for control (default 4190)
  -h, --help                            help for inject
      --image-pull-policy string        Docker image pull policy (default "IfNotPresent")
      --inbound-port uint               proxy port to use for inbound traffic (default 4143)
      --init-image string               Conduit init container image name (default "gcr.io/runconduit/proxy-init")
      --outbound-port uint              proxy port to use for outbound traffic (default 4140)
      --proxy-image string              Conduit proxy container image name (default "gcr.io/runconduit/proxy")
      --proxy-log-level string          log level for the proxy (default "warn,conduit_proxy=info")
      --proxy-uid int                   Run the proxy under this user ID (default 2102)
      --skip-inbound-ports uintSlice    ports that should skip the proxy and send directly to the applicaiton (default [])
      --skip-outbound-ports uintSlice   outbound ports that should skip the proxy (default [])

Global Flags:
  -n, --conduit-namespace string   namespace in which Conduit is installed (default "conduit")
      --verbose                    turn on debug logging

```

### LINKED ISSUE #390: diff code in test_helper.go crashes on certain input
### Test code
```go
diffCompare(t, "\n\n", "\n")
```

### Output
```bash
panic: runtime error: slice bounds out of range [recovered]
	panic: runtime error: slice bounds out of range

goroutine 50 [running]:
testing.tRunner.func1(0xc4202f85a0)
	/usr/local/Cellar/go/1.10/libexec/src/testing/testing.go:742 +0x29d
panic(0x19f5ee0, 0x21a6370)
	/usr/local/Cellar/go/1.10/libexec/src/runtime/panic.go:505 +0x229
github.com/runconduit/conduit/vendor/github.com/sergi/go-diff/diffmatchpatch.(*DiffMatchPatch).patchMake2(0xc4205cdd88, 0xc42038e5f1, 0x1, 0xc420096720, 0x2, 0x4, 0xc4205cdd88, 0xc42038e5f8, 0x1)
	/Users/sig/code/go/src/github.com/runconduit/conduit/vendor/github.com/sergi/go-diff/diffmatchpatch/patch.go:171 +0xb33
github.com/runconduit/conduit/vendor/github.com/sergi/go-diff/diffmatchpatch.(*DiffMatchPatch).PatchMake(0xc4205cdd88, 0xc4205cde08, 0x2, 0x2, 0x1, 0x10c5401, 0xc420096720)
	/Users/sig/code/go/src/github.com/runconduit/conduit/vendor/github.com/sergi/go-diff/diffmatchpatch/patch.go:131 +0x48a
github.com/runconduit/conduit/cli/cmd.diffCompare(0xc4202f85a0, 0xc4205cdea8, 0x2, 0xc42038e5f1, 0x1)
	/Users/sig/code/go/src/github.com/runconduit/conduit/cli/cmd/test_helper.go:13 +0x1d0
```

### Background

https://github.com/runconduit/conduit/pull/389#discussion_r169155485

Curiously, this works:
```go
diffCompare(t, "\n", "\n\n")
```

### PR DESCRIPTION
**Pull request by deebo91**
When the `inject` command is used on a YAML file that is invalid, it prints out an invalid YAML file with the injected proxy. This may give a false indication to the user that the inject was successful even though the inject command prints out an error message further down the terminal window. This PR fixes #303 and contains a test input and output file that indicates what should be shown.

This PR also fixes #390.

### CODE REVIEW

**Comment by briansmith** [comment]
It seems to me that error text, including the usage text, should be written to stderr, not stdout. Thus, I would expect this test to verify that *nothing* is written to stdout and that *something* is written to stderr. I don't think we should have a golden file for the usage message because then everybody would have to update the golden file whenever they add or change a parameter, which seems too annoying.

**Comment by briansmith** [comment]
I added @pcalcado and @klingerf as reviewers because they have been working on some similar tests and might have thoughts, and because @pcalcado is the reporter.

File: cli/cmd/inject_test.go [hunk 1]
```diff
@@ -33,4 +37,29 @@ func TestInjectYAML(t *testing.T) {
...
+
+		goldenFileBytes, err := ioutil.ReadFile("testdata/inject_gettest_deployment.golden")
+		if err != nil {
+			t.Fatalf("Unexpected error: %v", err)
+		}
+
+		actualOutput := buf.String()
+
+		expectedOutput := string(goldenFileBytes)
+		diffCompare(t, strings.TrimSpace(actualOutput), strings.TrimSpace(expectedOutput))
```
Comment (siggy) [inline cli/cmd/inject_test.go]: i can see that removing these `TrimSpace` calls crashes `test_helper.go`/`go-diff`. perhaps we have two separate issues?
1) why is the expected output different from the actual? is this a line-ending problem?
2) why does our test crash if the outputs are different?

File: cli/cmd/inject.go [hunk 2]
```diff
@@ -56,7 +57,17 @@ with 'conduit inject'. e.g. curl http://url.to/yml | conduit inject -
 				return err
 			}
 		}
-		return InjectYAML(in, os.Stdout)
+
+		postInjectBuf := new(bytes.Buffer)
```
Comment (siggy) [inline cli/cmd/inject.go]: consider `postInjectBuf := &bytes.Buffer{}`

File: cli/cmd/inject_test.go (hunk 1 above)
Comment (briansmith) [reply cli/cmd/inject_test.go]: > why does our test crash if the outputs are different?

AFAICT, the diff stuff has always been broken. I forgot to file an issue about it but it has been the case every time I tried it.

Comment (siggy) [reply cli/cmd/inject_test.go]: I've filed #390 to track this item 2.

Re: item 1, the expected output contains a single trailing newline, the actual output contains two trailing newlines. I think we should change either the expected or actual in this PR.

Comment (deebo91) [reply cli/cmd/inject_test.go]: @siggy I think it might be, I am not entirely sure. Trying to compare the two outputs in my editor is a little challenging since vscode seems to be removing newline characters. Do you think there is a better way to solve it than using `TrimSpace`?

File: cli/cmd/testdata/inject_gettest_deployment.golden [hunk 3]
```diff
@@ -0,0 +1,22 @@
+Error: error converting YAML to JSON: yaml: line 14: did not find expected key
+Usage:
```
Comment (briansmith) [inline cli/cmd/testdata/inject_gettest_deployment.golden]: Further thought: Regardless of whether we print the error message to stdout or stderr (and it really should be stderr), we should not print the "Usage" message on this kind of error.

File: cli/cmd/inject_test.go (hunk 1 above)
Comment (siggy) [reply cli/cmd/inject_test.go]: for item 2, the fix is a change in `diffCompare`:
```
-               patches := dmp.PatchMake(expected, diffs)
+               patches := dmp.PatchMake(actual, diffs)
```

File: cli/cmd/inject.go [hunk 4]
```diff
@@ -56,10 +57,21 @@ with 'conduit inject'. e.g. curl http://url.to/yml | conduit inject -
...
-		return InjectYAML(in, os.Stdout)
+		return runInjectCmd(in, os.Stderr, os.Stdout)
 	},
 }
 
+func runInjectCmd(input io.Reader, errWriter io.Writer, outWriter io.Writer) error {
+	postInjectBuf := &bytes.Buffer{}
+	err := InjectYAML(input, postInjectBuf)
+	if err != nil {
+		fmt.Fprintf(errWriter, "Error injecting conduit proxy: %v", err)
```
Comment (siggy) [inline cli/cmd/inject.go]: need newline: `...proxy: %v\n"`

File: cli/cmd/testdata/inject_gettest_deployment.input [hunk 5]
```diff
@@ -0,0 +1,59 @@
...
+apiVersion: apps/v1beta1
+kind: Deployment
+metadata:
+  name: get-test-deploy-injected-1
+  namespace: get-test
+spec:
+  replicas: 1
+  selector:
+      matchLabels:
+        app: get-test
```
Comment (siggy) [inline cli/cmd/testdata/inject_gettest_deployment.input]: apologies did not noticed this on first review, can you shrink this file down to something simpler that yields the same error, for example:
```yaml
---
kind: Deployment
spec:
  template:
      metadata:
        labels:
          app: get-test
    spec:
      containers: []
```

Comment (deebo91) [reply cli/cmd/testdata/inject_gettest_deployment.input]: Yep, can definitely do that. Thanks for the suggestion

Comment (briansmith) [reply cli/cmd/testdata/inject_gettest_deployment.input]: > can you shrink this file down to something simpler that yields the same error

We need a test case where there is at least one valid object before the invalid object.

File: cli/cmd/inject.go [hunk 6]
```diff
@@ -56,10 +57,21 @@ with 'conduit inject'. e.g. curl http://url.to/yml | conduit inject -
 				return err
 			}
 		}
-		return InjectYAML(in, os.Stdout)
+		return runInjectCmd(in, os.Stderr, os.Stdout)
 	},
 }
 
+func runInjectCmd(input io.Reader, errWriter io.Writer, outWriter io.Writer) error {
```
Comment (briansmith) [inline cli/cmd/inject.go]: This function should not have `error` as its return type. Notice it always returns `nil` so the return value is useless.

File: cli/cmd/inject.go [hunk 7]
```diff
@@ -56,10 +57,21 @@ with 'conduit inject'. e.g. curl http://url.to/yml | conduit inject -
...
+	postInjectBuf := &bytes.Buffer{}
+	err := InjectYAML(input, postInjectBuf)
+	if err != nil {
+		fmt.Fprintf(errWriter, "Error injecting conduit proxy: %v", err)
+		return nil //Return nil so we do not print usage information in the command
```
Comment (briansmith) [inline cli/cmd/inject.go]: You need to exit with a non-zero exit code.

File: cli/cmd/inject.go [hunk 8]
```diff
@@ -56,10 +57,21 @@ with 'conduit inject'. e.g. curl http://url.to/yml | conduit inject -
...
+	}
+	io.Copy(outWriter, postInjectBuf)
```
Comment (briansmith) [inline cli/cmd/inject.go]: You need to check the return value of Copy and exit with a non-zero exit code on error.

File: cli/cmd/inject.go [hunk 9]
```diff
@@ -168,6 +180,7 @@ func injectPodTemplateSpec(t *v1.PodTemplateSpec) bool {
 	t.Spec.InitContainers = append(t.Spec.InitContainers, initContainer)
 
 	return true
+
```
Comment (briansmith) [inline cli/cmd/inject.go]: Extraneous blank line should be removed..

File: cli/cmd/inject.go [hunk 10]
```diff
@@ -56,10 +57,21 @@ with 'conduit inject'. e.g. curl http://url.to/yml | conduit inject -
 				return err
 			}
 		}
-		return InjectYAML(in, os.Stdout)
+		return runInjectCmd(in, os.Stderr, os.Stdout)
```
[the remark this answers is not in the document]
Comment (briansmith) [reply cli/cmd/inject.go]: I see that if you want to test the output to stderr then my suggestion doesn't work. In that case you can just have runInjectCmd return the exit code for `os.Exit()`, so that you can write:

```go
exitCode := runInjectCmd(in, os.Stderr, os.Stdout)
os.Exit(exitCode)
return nil
```

File: cli/cmd/inject.go [hunk 11]
```diff
@@ -57,19 +57,26 @@ with 'conduit inject'. e.g. curl http://url.to/yml | conduit inject -
...
 		}
-		return runInjectCmd(in, os.Stderr, os.Stdout)
+		exitCode := runInjectCmd(in, os.Stderr, os.Stdout)
+		os.Exit(exitCode)
+		return nil
 	},
 }
 
-func runInjectCmd(input io.Reader, errWriter io.Writer, outWriter io.Writer) error {
+// Returns the integer representation of os.Exist code; 0 on success and 1 on failure.
```
Comment (briansmith) [inline cli/cmd/inject.go]: s/Exist/Exit/

File: cli/cmd/inject_test.go [hunk 12]
```diff
@@ -51,7 +51,7 @@ func TestInjectYAML(t *testing.T) {
 		outBuffer := &bytes.Buffer{}
 		expectedErrorMsg := `Error injecting conduit proxy: error converting YAML to JSON: yaml: line 14: did not find expected key`
 
-		in, err := os.Open("testdata/inject_gettest_deployment.input")
+		in, err := os.Open("testdata/inject_gettest_deployment.input.yml")
```
Comment (briansmith) [inline cli/cmd/inject_test.go]: In the call to `runInjectCmd()` below, test the return value. I.e. verify that it is 1 on failure and 0 on success.

File: cli/cmd/inject.go (hunk 11 above)
Comment (deebo91) [reply cli/cmd/inject.go]: 🤦‍♂️ Thanks for spelling check!

File: cli/cmd/inject_test.go [hunk 13]
```diff
@@ -45,4 +45,24 @@ func TestInjectYAML(t *testing.T) {
 			diffCompare(t, actualOutput, expectedOutput)
 		})
 	}
+
```
Comment (briansmith) [inline cli/cmd/inject_test.go]: Another nit: There's no need for this test, the way it is structured, to be in `TestInjectYAML`. It should be in a function `TestRunInjectCmd`.

File: cli/cmd/inject_test.go [hunk 14]
```diff
@@ -46,3 +46,48 @@ func TestInjectYAML(t *testing.T) {
...
+		}
+
+		if len(outBuffer.Bytes()) != 0 {
+			t.Fatalf("Expected output buffer to be empty but got: \n%v", outBuffer)
+		}
+
+		actualErrorMsg := errBuffer.String()
+		diffCompare(t, actualErrorMsg, expectedErrorMsg)
+	})
+	t.Run("Do not print invalid YAML on inject error", func(t *testing.T) {
```
Comment (briansmith) [inline cli/cmd/inject_test.go]: The string passed to t.Run() is not right for this test case.

More generally, it's better to write these tests as table-driven tests since they are much easier to review and expand upon in future work:

```go
    testCases := []struct {
 		inputFileName  string
 		stdoutFileName string
 		stderrGoldenFileName string
		exitCode int
 	}{
 		{ <inputs/outputs for the passing test case> },
 		{ <inputs/outputs for the failing  test case> },
 	}
	
	for i, tc := range(testCases) {
	    t.Run(...) {
		    // Your test code here.
		}
	}
```

(I didn't `go fmt` this.)

File: cli/cmd/inject_test.go [hunk 15]
```diff
@@ -46,3 +46,49 @@ func TestInjectYAML(t *testing.T) {
...
+			exitCode:             0,
+		},
+	}
+
+	for i, tc := range testCases {
+		t.Run(fmt.Sprintf("%d: %s", i, tc.inputFileName), func(t *testing.T) {
+			errBuffer := &bytes.Buffer{}
+			outBuffer := &bytes.Buffer{}
+
+			in, err := os.Open(fmt.Sprintf("testData/%s", tc.inputFileName))
```
Comment (siggy) [inline cli/cmd/inject_test.go]: `testdata`

File: cli/cmd/test_helper.go [hunk 16]
```diff
@@ -9,9 +12,29 @@ import (
...
 		patches := dmp.PatchMake(expected, diffs)
 		patchText := dmp.PatchToText(patches)
 		t.Fatalf("Unexpected output:\n%+v", patchText)
 	}
 }
+
+func readGoldenTestFile(t *testing.T, testDirWithTrailingSlash string, goldenFileName string) string {
+	var fileData string
+
+	if goldenFileName != "" {
```
Comment (siggy) [inline cli/cmd/test_helper.go]: i would fail the test if `goldenFileName` == ""

File: cli/cmd/test_helper.go [hunk 17]
```diff
@@ -9,9 +12,29 @@ import (
...
 		dmp := diffmatchpatch.New()
-		diffs := dmp.DiffMain(actual, expected, true)
+		diffs := dmp.DiffMain(expected, actual, true)
 		patches := dmp.PatchMake(expected, diffs)
 		patchText := dmp.PatchToText(patches)
 		t.Fatalf("Unexpected output:\n%+v", patchText)
 	}
 }
+
+func readGoldenTestFile(t *testing.T, testDirWithTrailingSlash string, goldenFileName string) string {
```
Comment (siggy) [inline cli/cmd/test_helper.go]: probably can name this something more generic, not specific to golden files.

File: cli/cmd/inject_test.go (hunk 15 above)
Comment (deebo91) [reply cli/cmd/inject_test.go]: good catch. It's weird that it still proceed through the test even though the directory name was different than intended.

File: cli/cmd/test_helper.go (hunk 16 above)
Comment (deebo91) [reply cli/cmd/test_helper.go]: There are some cases where a file name isn't provided by the test case in a table driven test and so we do not want to fail the test. For example:
```go
expectedStdOutResult := readGoldenTestFile(t, "testdata/", tc.stdOutGoldenFileName)
...
expectedStdErrResult := readGoldenTestFile(t, "testdata/", tc.stdErrGoldenFileName)
...
```
In one test case, we can have a test return data for `stdOut` but return nothing for `stdErr`. That test is considered valid because that is the intended functionality so we want to be able to load the golden file for `stdOut` and just return and an empty string for `stdErr` to be used to validate the test.

Comment (briansmith) [reply cli/cmd/test_helper.go]: > In one test case, we can have a test return data for stdOut but return nothing for stdErr. That test is considered valid because that is the intended functionality so we want to be able to load the golden file for stdOut and just return and an empty string for stdErr to be used to validate the test.

Probably the best way to address @siggy's feedback is to name the function "readOptionalTestFile" and document in a comment what happens when the filename is empty.

File: cli/cmd/test_helper.go (hunk 17 above)
Comment (siggy) [reply cli/cmd/test_helper.go]: also consider hard-coding `testDirWithTrailingSlash` as it's always `testdata/`
