### PR TITLE
Proxy: Fall back to using DNS when Destination service can't find service.

### LINKED ISSUE #155: Destinations service doesn't discover services outside the local cluster
If the DNS name sent in a query to the Destinations service has a suffix of "cluster.local" or whatever the current cluster domain name is, the Destination service should use the local k8s API server's Services API to discover the service. There are two cases:

* If the service is not an "external" service then the Destinations service should use the EndPoints API to watch the addresses for the service. This works now.

* If the service is an "external" service, then the Destination service should use DNS to discover the addresses for the service, as kube-proxy would. It should periodically poll DNS to get a similar effect toa watch on the EndPoints API for internal services. This doesn't work now.

If the DNS name sent in the query to the Destinations service doesn't end with "cluster.local" or the local cluster domain name, then the Destinations service should skip using the Services API and assume that it is an "external" service. This doesn't work now.

### PR DESCRIPTION
**Pull request by briansmith**
Fixes #155.

### CODE REVIEW

**Comment by briansmith** [comment]
This PR is based on the branch for PR #674. Once #674 is merged, I will rebase this onto master.

File: proxy/src/control/discovery.rs [hunk 1]
```diff
@@ -58,6 +63,7 @@ pub struct DiscoveryWork<T: HttpService<ResponseBody = RecvBody>> {
 struct DestinationSet<T: HttpService<ResponseBody = RecvBody>> {
     addrs: Exists<Cache<SocketAddr>>,
     query: Option<DestinationServiceQuery<T>>,
+    dns_query: Option<IpAddrListFuture>,
```
Comment (olix0r) [inline proxy/src/control/discovery.rs]: just to confirm my understanding...  it's the case that when we have a `dns_query`, we're guaranteed to also have a `query`?  Does it make sense to have a single `Query<T>`  type that holds both the `DestinationServiceQuery<T>` and `Option<IpAddrListFuture>`? tioli... just asking questions as i read.

File: proxy/src/dns.rs [hunk 2]
```diff
@@ -107,7 +143,14 @@ impl Future for IpAddrFuture {
...
 
+impl Future for IpAddrListFuture {
+    type Item = Response;
+    type Error = abstract_ns::Error;
 
+    fn poll(&mut self) -> Result<Async<<Self as Future>::Item>, <Self as Future>::Error> {
+        self.0.poll()
+    }
+}
 #[cfg(test)]
```
Comment (olix0r) [inline proxy/src/dns.rs]: nit: newline after the impl, por favor.

File: proxy/src/control/discovery.rs (hunk 1 above)
Comment (briansmith) [reply proxy/src/control/discovery.rs]: > It's the case that when we have a dns_query, we're guaranteed to also have a query?

No. When we first create the `DestinationSet`, we check if the query is `None` and then automatically create the `dns_query` if it is None. So all combinations are possible.

File: proxy/src/dns.rs (hunk 2 above)
Comment (briansmith) [reply proxy/src/dns.rs]: Thanks. Fixed.

File: proxy/src/control/discovery.rs (hunk 1 above)
Comment (hawkw) [reply proxy/src/control/discovery.rs]: Hmm. Are there specific states in which we would expect a given combination of `None` and `Some`? If so we might want to consider an `enum` that encodes those states and the allowable transitions between them...

File: proxy/src/dns.rs [hunk 3]
```diff
@@ -107,6 +143,14 @@ impl Future for IpAddrFuture {
     }
 }
 
+impl Future for IpAddrListFuture {
```
Comment (hawkw) [inline proxy/src/dns.rs]: Is there a reason `IpAddrListFuture` is a newtype rather than a type alias? If it were a type alias, the impl of `Future` for it that just calls the wrapped future wouldn't be necessary?

Comment (briansmith) [reply proxy/src/dns.rs]: > Is there a reason IpAddrListFuture is a newtype rather than a type alias? If it were a type alias, the impl of Future for it that just calls the wrapped future wouldn't be necessary?

I switched it to be the way you recommend. Thanks.

File: proxy/src/control/discovery.rs (hunk 1 above)
Comment (briansmith) [reply proxy/src/control/discovery.rs]: `(None, None)` is not a valid state but intermittently we do have `(None, None)` sometimes because of the uses of `take` in `poll_destinations()`.

Comment (briansmith) [reply proxy/src/control/discovery.rs]: As far as the transitions go:

`(Some, None)` is a valid initial state, when the name is of a form for which we'd query the Destination service.
`(None, Some)` is a valid initial state, when that's not the case.

`(Some, None) => (Some, Some)` when the destination service indicates that the service doesn't exist.
`(Some, Some) => (Some, None)` when the destination service indicates the service exists after previously telling us it didn't.

`(None, None)` is a frequent intermediate state but it isn't a valid state in general.

We could try to encode this into a typed state machine, but I think that would impede immediately-upcoming work to generalize service discovery beyond the Destination service and DNS. I suggest we add that 3rd type of service discovery and do that refactoring before we fossilize the current design too much more. In particular, in the future it would be nice to not have `control::discovery` aware of the Destination service or DNS at all. But not yet, and not in this PR. :)

File: proxy/src/dns.rs [hunk 4]
```diff
@@ -72,20 +85,44 @@ impl Config {
...
-                trace!("resolve {}", name);
-                IpAddrFuture::DNS(self.0.resolve_host(&name.0))
+                trace!("resolve_one_ip {}", name);
+                IpAddrFuture::DNS(self.resolver.resolve_host(&name.0))
             }
             transport::Host::Ip(addr) => IpAddrFuture::Fixed(addr),
         }
     }
+
+    pub fn resolve_all_ips(&self, delay: Duration, host: &Name) -> IpAddrListFuture {
```
Comment (olix0r) [inline proxy/src/dns.rs]: I don't have a strong feeling on this one way or another, but did you consider making this return an `IpAddrListStream` instead (i.e. pushing the TTL/looping down into stream impl). The main advantage of this, I think, would be that the `poll_dns` implementation in `control::discovery` could be moved into the `dns` module, which (I think) means that discovery won't have to change to support TTLs, etc...

File: proxy/src/control/discovery.rs (hunk 1 above)
Comment (olix0r) [reply proxy/src/control/discovery.rs]: 👍

File: proxy/src/control/discovery.rs [hunk 5]
```diff
@@ -372,23 +396,57 @@ impl<T> DestinationSet<T>
...
+        authority: &DnsNameAndPort)
+    {
+        trace!("resetting DNS query for {} with delay {:?}", authority.host, delay);
+        self.reset_on_next_modification();
+        self.dns_query = Some(dns_resolver.resolve_all_ips(delay, &authority.host));
+    }
+
+    fn poll_destination_service(
+        &mut self,
+        dns_resolver: &dns::Resolver,
```
Comment (olix0r) [inline proxy/src/control/discovery.rs]: it's mildly surprising that this takes a `dns_resolver` (as I'd expect this to... only poll the destination service).  It seems this is necessary so that it can initialize a dns query, which is polled in the followup call to `poll_dns.`  I'm fine with this as it is, but it seems like something it would be nice to separate further in a future change.

File: proxy/src/dns.rs (hunk 4 above)
Comment (olix0r) [reply proxy/src/dns.rs]: to be clear: it would be fine to do this in a followup; i'm just curious if you avoided pushing the looping down for a specific reason.

File: proxy/src/control/discovery.rs (hunk 1 above)
Comment (hawkw) [reply proxy/src/control/discovery.rs]: Okay, yeah, that seems entirely reasonable to me --- I was just curious. 👍

File: proxy/src/dns.rs (hunk 4 above)
Comment (briansmith) [reply proxy/src/dns.rs]: > to be clear: it would be fine to do this in a followup; i'm just curious if you avoided pushing the looping down for a specific reason.

Converting this to return a Stream is a good idea. I was meaning to follow up with a change that did that, but I am running short on time. If it is OK to do that as a follow-up, let's do so.

**Comment by briansmith** [comment]
@klingerf Could you please review the changes under `test/`, specifically egress_test.go and the associated YAML file?

I elected not to run the entire combination or protocol/method/hostname for the "less than three labels" case, as that's not the main point of that sub-test.

**Comment by siggy** [comment]
@olix0r Yup, the absence of a `dst_*` label will work. We may want to consider an explicit `dns="foo.com"` label, if we want to differentiate between a valid external DNS metric, and a malformed internal metric that's just missing its `dst_*` labels.

**Comment by briansmith** [comment]
#725 should be merged before this is merged.
